type CompanyRow={id:string;source_id:string|null;name:string;name_en:string|null;city:string;topics_json:string;mark:string;summary:string;note:string;url:string;opportunity_url:string|null;priority:string;source_verified_at:string|null};
type SourceRow={id:string;url:string;enabled:number;last_success_at:string|null;last_checked_at:string|null;last_status_code:number|null;consecutive_failures:number};
type OpportunityRow={id:string;source_id:string|null;name:string;org:string;kind:string;status:string;location:string;deadline:string;deadline_status:string;why:string;action:string;tags_json:string;url:string;source_verified_at:string|null};
export async function GET(){try{const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("D1 binding DB is unavailable");const[companies,sources,opportunities]=await Promise.all([
env.DB.prepare(`SELECT id,source_id,name,name_en,city,topics_json,mark,summary,note,url,opportunity_url,priority,source_verified_at FROM institutions WHERE published=1 AND institution_type='company' ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,sort_order`).all<CompanyRow>(),
env.DB.prepare(`SELECT id,url,enabled,last_success_at,last_checked_at,last_status_code,consecutive_failures FROM sources WHERE organization_type='company' ORDER BY name`).all<SourceRow>(),
env.DB.prepare(`SELECT id,source_id,name,org,kind,status,location,deadline,deadline_status,why,action,tags_json,url,source_verified_at FROM opportunities WHERE published=1 AND source_id IN (SELECT id FROM sources WHERE organization_type='company') ORDER BY CASE status WHEN '立即行动' THEN 0 WHEN '持续关注' THEN 1 ELSE 2 END,created_at DESC`).all<OpportunityRow>()]);
const sourceMap=new Map(sources.results.map((item)=>[item.id,item])),companySourceIds=new Set(companies.results.map((item)=>item.source_id).filter(Boolean)),published=opportunities.results.filter((item)=>item.source_id&&companySourceIds.has(item.source_id));return Response.json({generatedAt:new Date().toISOString(),counts:{companies:companies.results.length,officialSources:companySourceIds.size,publishedOpportunities:published.length},companies:companies.results.map((item)=>{const source=item.source_id?sourceMap.get(item.source_id):null;return{...item,nameEn:item.name_en,scope:isChina(item.city)?"中国":"全球",topics:array(item.topics_json),opportunityUrl:item.opportunity_url,sourceVerifiedAt:item.source_verified_at,source:source?{...source,enabled:Boolean(source.enabled),lastSuccessAt:source.last_success_at,lastCheckedAt:source.last_checked_at,lastStatusCode:source.last_status_code,consecutiveFailures:source.consecutive_failures}:null,opportunities:published.filter((row)=>row.source_id===item.source_id).map(format)}})},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error(JSON.stringify({event:"radar.ai_companies.failed",error:message(error)}));return Response.json({error:"AI company intelligence is temporarily unavailable"},{status:503})}}
function isChina(city:string){return/[\u4e00-\u9fff]/.test(city)&&!city.includes("London")}
function array(value:string){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}}
function format(row:OpportunityRow){return{...row,deadlineStatus:row.deadline_status,tags:array(row.tags_json),sourceVerifiedAt:row.source_verified_at}}
function message(error:unknown){return error instanceof Error?error.message.slice(0,500):String(error).slice(0,500)}
