ALTER TABLE `opportunities` ADD `masters_eligible` integer DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE `opportunities` ADD `eligibility_details` text DEFAULT '以官方岗位要求为准' NOT NULL;--> statement-breakpoint
ALTER TABLE `opportunities` ADD `phd_bridge_details` text;
--> statement-breakpoint
UPDATE `sources`
SET `priority` = 'high', `check_interval_hours` = 6
WHERE `id` IN (
  'shlab-joint-phd','shlab-jobs','oppo-health-ml','oppo-health-algorithm',
  'bytedance-seed','huawei-campus','tencent-campus'
);
--> statement-breakpoint
INSERT OR IGNORE INTO `sources`
(`id`,`name`,`source_type`,`coverage`,`organization_type`,`regions_json`,`topics_json`,`description`,`priority`,`url`,`enabled`,`check_interval_hours`) VALUES
('oxford-research-jobs','牛津大学 Research Jobs','listing','phd','university','["UK"]','["科研助理","实验心理学","神经科学"]','牛津大学官方研究岗位入口，用于发现接受本科或硕士背景的 Research Assistant、Research Technician 等博士前研究岗位。','critical','https://www.ox.ac.uk/about/jobs',1,6),
('cambridge-current-jobs','剑桥大学 Current Research Jobs','listing','phd','university','["UK"]','["科研助理","心理学","认知神经科学"]','剑桥大学官方招聘入口，用于跟踪 Psychology、MRC CBU、Clinical Neurosciences 等部门的 Research Assistant 岗位。','critical','https://www.cam.ac.uk/jobs/search',1,6),
('ucl-current-jobs','UCL Research Jobs','listing','phd','university','["UK"]','["科研助理","心理学","脑科学"]','UCL 官方招聘入口，用于跟踪 Faculty of Brain Sciences 与 Psychology and Language Sciences 的 Research Assistant 岗位。','critical','https://www.ucl.ac.uk/work-at-ucl/search-ucl-jobs',1,6),
('tsinghua-yao-neuro-ra-2026','清华生命学院姚骏实验室科研助理','detail','phd','university','["CN"]','["科研助理","神经生物学","精神疾病"]','清华生命学院官方科研助理招聘，明确要求神经生物学等相关专业硕士学位。','critical','https://life.tsinghua.edu.cn/info/1130/7782.htm',1,6),
('pku-aaib-brain-ra-2026','北大成都前沿交叉研究院脑认知科研助理','detail','phd','research','["CN"]','["科研助理","脑认知","脑机接口"]','北京大学成都前沿交叉生物技术研究院 2026 年下半年官方招聘，脑认知与脑疾病实验室科研助理本科及以上可申请。','critical','https://aaib.pku.edu.cn/info/1008/1794.htm',1,6),
('hku-research-staff-jobs','香港大学 Research Staff Jobs','listing','phd','university','["HK"]','["科研助理","心理学","神经科学"]','香港大学官方 Research Staff 职位目录，持续列出 RA I/II、心理学、医学与行为科学岗位。','critical','https://jobs.hku.hk/cw/en/Search/?category=research+staff&search-keyword=&subscribe=true',1,6),
('hku-psych-ra-536755','香港大学心理学系科研助理 536755','detail','phd','university','["HK"]','["科研助理","心理学","统计分析"]','港大心理学系官方 Research Assistant I/II 招聘，本科或以上学历可申请。','critical','https://jobs.hku.hk/cw/en/job/536755/senior-research-assistant-research-assistant-iii',1,6),
('hku-psycho-oncology-ra-536719','香港大学心理肿瘤学科研助理 536719','detail','phd','university','["HK"]','["科研助理","心理学","行为科学"]','港大公共卫生学院心理肿瘤学与行为科学官方 Research Assistant II 招聘，本科或以上学历可申请。','critical','https://jobs.hku.hk/en/job/536719/',1,6),
('fudan-brain-technology-ra-2026','复旦大学脑智研究院研究助理','detail','phd','university','["CN"]','["科研助理","神经生物学","脑科学"]','复旦大学脑智研究院官方研究助理招聘，要求神经生物学、医学或药学硕士及以上。','critical','https://hr.fudan.edu.cn/f9/d0/c15370a784848/page.htm',1,6),
('siat-brain-cognition-ra-2026','深圳先进院脑认知研究助理','detail','phd','research','["CN"]','["科研助理","脑认知","神经科学"]','中国科学院深圳先进院脑认知与脑疾病研究所官方研究助理招聘，要求硕士及以上。','critical','https://cxqjzx.siat.ac.cn/siat/2026-05/22/article_2026052210453244934.html',1,6);
--> statement-breakpoint
INSERT OR IGNORE INTO `opportunities`
(`id`,`source_id`,`name`,`org`,`kind`,`status`,`fit`,`location`,`deadline`,`masters_eligible`,`eligibility_details`,`phd_bridge_details`,`why`,`action`,`tags_json`,`url`) VALUES
('oxford-research-assistant-watch','oxford-research-jobs','Oxford Research Assistant 滚动岗位','牛津大学','科研助理','持续关注','高度匹配','Oxford','官方岗位库滚动更新；以具体职位截止时间为准',1,'硕士可申请其中明确接受本科或硕士学历的 Research Assistant / Research Technician；逐岗核对签证与学科要求。','可积累英国实验室经历、方法训练和推荐信；不代表自动获得本校博士录取。','牛津官方研究岗位入口会持续出现心理学、精神健康、神经科学及数据研究职位，具体空缺随项目经费变化。','在官方页面筛选 Research 和 Research Assistant；优先核对学历、签证担保、合同期与是否支持论文产出。','["科研助理","英国","实验心理学","博士过渡"]','https://www.ox.ac.uk/about/jobs'),
('cambridge-research-assistant-watch','cambridge-current-jobs','Cambridge Research Assistant 滚动岗位','剑桥大学','科研助理','持续关注','高度匹配','Cambridge','官方岗位库滚动更新；以具体职位截止时间为准',1,'硕士可申请其中明确接受本科或硕士学历的 Research Assistant；Research Associate 通常要求博士，须注意职级差异。','可在 Psychology、MRC CBU 或 Clinical Neurosciences 积累研究经历，并为后续博士申请形成导师推荐与成果。','剑桥官方职位库持续发布 Research Assistant；系统重点跟踪心理学、认知与临床神经科学相关岗位。','用 Research Assistant、Psychology、Cognition、Neuroscience 组合检索；不要把要求博士的 Research Associate 当作硕士岗位。','["科研助理","英国","认知神经","博士过渡"]','https://www.cam.ac.uk/jobs/search'),
('ucl-research-assistant-watch','ucl-current-jobs','UCL Research Assistant 滚动岗位','UCL','科研助理','持续关注','高度匹配','London','官方岗位库滚动更新；以具体职位截止时间为准',1,'硕士可申请符合具体专业、研究技能和工作权要求的 Research Assistant；逐岗核对海外申请与签证条件。','UCL 脑科学研究群规模大，岗位经历可强化实验、统计、影像和推荐信，但博士申请仍需独立竞争。','UCL 官方职位入口支持按 research、fixed-term 和 part-time 筛选，适合作为博士前研究工作的长期监控入口。','优先检索 Brain Sciences、PALS、ICN、Imaging Neuroscience，并订阅职位提醒。','["科研助理","英国","脑科学","博士过渡"]','https://www.ucl.ac.uk/work-at-ucl/search-ucl-jobs'),
('tsinghua-yao-neuro-ra','tsinghua-yao-neuro-ra-2026','姚骏实验室神经科学科研助理','清华大学生命科学学院','科研助理','立即行动','高度匹配','北京','官方未标注截止日期｜招满为止',1,'要求神经生物学、细胞生物学、分子生物学或遗传学等相关专业硕士学位；有神经科学、动物行为或电生理经验优先。','岗位要求稳定工作 2—3 年，可形成完整项目周期、实验技能和论文协作经历，适合再申请神经科学博士。','研究精神疾病、神经退行性疾病、神经胶质细胞及类器官，招聘 1—3 名科研助理。','立即发送简历并突出实验技术、独立数据分析和稳定工作计划；邮件主题按官方要求填写。','["科研助理","清华","神经科学","硕士可申请"]','https://life.tsinghua.edu.cn/info/1130/7782.htm'),
('pku-aaib-brain-ra','pku-aaib-brain-ra-2026','脑认知与脑疾病实验室科研助理','北京大学成都前沿交叉生物技术研究院','科研助理','立即行动','高度匹配','成都','2026 下半年招聘｜官方未标注统一截止日期',1,'本科及以上学历；生命科学、神经科学相关专业优先，具有数据处理、编程、动物行为、VR 或脑机接口经验者优先。','可参与脑认知、动物行为、在体电极、钙成像和闭环脑机接口实验，为申请脑科学或 BCI 博士补充项目证据。','官方招聘包含脑认知与脑疾病实验室研究助理，工作涉及实验准备、数据整理和基础分析。','用研究型简历突出心理实验、数据分析和编程能力；投递前向官方邮箱确认岗位仍有名额。','["科研助理","北大","脑认知","脑机接口"]','https://aaib.pku.edu.cn/info/1008/1794.htm'),
('hku-psych-ra-536755-opportunity','hku-psych-ra-536755','心理学系 Research Assistant I/II','香港大学心理学系','科研助理','立即行动','高度匹配','香港','2026.08.09（香港时间）',1,'心理学或相关专业本科及以上；要求中英文沟通能力，并具备 SPSS、R 等基础统计软件知识。','一年期且可视表现及经费续约，能够积累心理学研究、数据分析和推荐信，但需自行规划后续博士申请。','港大心理学系全职科研助理岗位，面向心理学及相关专业，本科或以上学历可申请。','立即准备英文 CV、成绩单和统计分析项目证据，并在官方系统截止前提交。','["科研助理","香港","心理学","硕士可申请"]','https://jobs.hku.hk/cw/en/job/536755/senior-research-assistant-research-assistant-iii'),
('hku-psycho-oncology-ra-536719-opportunity','hku-psycho-oncology-ra-536719','心理肿瘤学与行为科学 Research Assistant II','香港大学公共卫生学院','科研助理','立即行动','高度匹配','香港','2026.08.31（香港时间）',1,'心理学、社会科学、公共卫生或相关专业本科及以上；粤语、中英文沟通和基础统计/SPSS 能力重要。','可积累患者招募、问卷访谈、队列与干预研究、数据分析经历，适合临床或健康心理学博士准备。','一年期全职岗位，参与心理肿瘤学的受试者招募、问卷访谈、分析、研究文档和项目进度管理。','立即投递英文 CV；重点说明粤语能力、受试者研究、统计软件和伦理合规经验。','["科研助理","香港","健康心理","行为科学"]','https://jobs.hku.hk/en/job/536719/'),
('fudan-brain-technology-ra','fudan-brain-technology-ra-2026','脑智研究院神经生物学研究助理','复旦大学脑智研究院','科研助理','立即行动','高度匹配','上海','2026.09.15',1,'要求神经生物学、医学或药学硕士及以上，并具备神经生物、单细胞/空间组学、脑片电生理与显微注射中的至少两项专长。','参与平台建设、实验技术、论文撰写和项目申报，可为神经科学博士申请补充高质量实验与合作成果。','招聘 2 名研究助理序列技术员，工作覆盖神经生物学实验平台、成像、神经网络重构和科研论文。','按官方格式提交中英文简历和个人陈述；明确列出两项以上匹配技术。','["科研助理","上海","复旦","神经生物学"]','https://hr.fudan.edu.cn/f9/d0/c15370a784848/page.htm'),
('siat-brain-cognition-ra','siat-brain-cognition-ra-2026','脑认知与脑疾病研究所研究助理','中国科学院深圳先进技术研究院','科研助理','立即行动','高度匹配','深圳','官方未标注截止日期｜招满为止',1,'要求已获得或近期将获得硕士学位；神经科学、生物信息、计算机、数学或统计等背景均可，需有论文或相关研究成果。','参与多模态组学、脑发育和情绪障碍研究，包含实验设计、数据采集分析和报告撰写，可形成博士申请研究主线。','招聘 1 名研究助理，方向涉及多模态组学、神经发育与情绪障碍，工作地点深圳光明区。','提交中英文简历；突出论文、神经科学/统计编程能力，并说明未来博士研究兴趣。','["科研助理","深圳","中科院","脑认知"]','https://cxqjzx.siat.ac.cn/siat/2026-05/22/article_2026052210453244934.html');
