INSERT OR IGNORE INTO sources (id,name,source_type,coverage,organization_type,regions_json,topics_json,description,priority,url,trust_level,enabled,check_interval_hours) VALUES
('tcd-neuroscience','Trinity College Institute of Neuroscience','listing','mixed','university','["IE"]','["神经科学","认知","脑成像"]','Trinity College Dublin 官方神经科学研究入口','high','https://www.tcd.ie/Neuroscience/',100,1,24),
('ucd-psychology-research','UCD School of Psychology Research','listing','mixed','university','["IE"]','["心理学","认知神经科学","行为科学"]','University College Dublin 心理学官方研究入口','high','https://www.ucd.ie/psychology/research/',100,1,24);

UPDATE institutions SET name_en='Shanghai Artificial Intelligence Laboratory',institution_type='research_institute',city='上海',topics_json='["人工智能","类脑智能","联培博士"]',opportunity_url='https://www.shlab.org.cn/joinus',priority='critical' WHERE id='shlab';
UPDATE institutions SET name_en='Peng Cheng Laboratory',institution_type='national_lab',city='深圳',topics_json='["人工智能","脑机接口","工程博士"]',opportunity_url='https://www.pcl.ac.cn/hr/recruit/',priority='critical' WHERE id='pengcheng';
UPDATE institutions SET name_en='UCL Faculty of Brain Sciences and Gatsby Computational Neuroscience Unit',institution_type='university',city='London',topics_json='["认知神经科学","计算神经科学","机器学习"]',opportunity_url='https://www.ucl.ac.uk/work-at-ucl/search-ucl-jobs',priority='critical' WHERE id='ucl-brain-sciences';
UPDATE institutions SET name_en='Department of Experimental Psychology, University of Oxford',institution_type='university',city='Oxford',topics_json='["实验心理学","认知神经科学","脑成像"]',opportunity_url='https://www.ox.ac.uk/about/jobs',priority='critical' WHERE id='oxford-experimental-psych';
UPDATE institutions SET name_en='MRC Cognition and Brain Sciences Unit, University of Cambridge',institution_type='research_institute',city='Cambridge',topics_json='["认知科学","脑成像","计算建模"]',opportunity_url='https://www.cam.ac.uk/jobs/search',priority='critical' WHERE id='cambridge-mrc-cbu-institution';

INSERT OR IGNORE INTO institutions (id,source_id,name,name_en,institution_type,city,topics_json,mark,summary,note,url,opportunity_url,priority,sort_order,published) VALUES
('fudan-istbi','fudan-brain-technology-ra-2026','复旦大学类脑智能科学与技术研究院','Institute of Science and Technology for Brain-Inspired Intelligence, Fudan University','university','上海','["脑科学","类脑智能","认知计算"]','脑智交叉','连接神经科学、认知科学、人工智能和类脑计算。','重点关注冯建峰团队、科研助理和博士培养入口。','https://istbi.fudan.edu.cn/','https://hr.fudan.edu.cn/', 'critical',10,1),
('sjtu-psych-institution','sjtu-psych','上海交通大学心理学院','School of Psychology, Shanghai Jiao Tong University','university','上海','["心理学","认知神经科学","心理健康"]','高校','覆盖基础与应用心理学、认知和临床相关研究。','适合持续跟踪博士招生、实验室和科研岗位。','https://psychology.sjtu.edu.cn/','https://psychology.sjtu.edu.cn/zsxx.html','high',20,1),
('siat-brain-institute','siat-brain-cognition-ra-2026','中国科学院深圳先进技术研究院脑认知与脑疾病研究所','Institute of Brain Cognition and Brain Disease, SIAT','cas_institute','深圳','["脑认知","脑疾病","脑机接口"]','中科院','依托脑解析与脑模拟设施，覆盖认知、灵长类模型和脑机接口。','重点关注硕士可申请的科研助理、博士和研究岗位。','https://www.siat.ac.cn/jggl/','https://www.siat.ac.cn/yjdw/rczp/','critical',10,1),
('tsinghua-sigs-institution','tsinghua-sigs','清华大学深圳国际研究生院','Tsinghua Shenzhen International Graduate School','university','深圳','["人工智能","生物医学工程","脑机接口"]','高校','清华在深圳的交叉研究与研究生培养平台。','适合跟踪博士招生、联合培养和实验室研究助理。','https://www.sigs.tsinghua.edu.cn/','https://www.sigs.tsinghua.edu.cn/zsjy/list.htm','critical',20,1),
('kcl-neuroscience','kcl-neuroscience-phd','伦敦国王学院神经科学研究体系','King’s College London Neuroscience','university','London','["神经科学","精神健康","脑成像"]','高校','覆盖基础、临床与转化神经科学。','关注 PhD、研究助理和精神健康交叉方向。','https://www.kcl.ac.uk/neuroscience','https://www.kcl.ac.uk/neuroscience/phd','high',40,1),
('imperial-brain-sciences','imperial-brain-sciences-phd','帝国理工学院脑科学系','Department of Brain Sciences, Imperial College London','university','London','["脑科学","神经技术","临床神经科学"]','高校','覆盖脑科学、神经技术和临床转化。','适合关注跨工程和医学的博士与研究岗位。','https://www.imperial.ac.uk/brain-sciences/','https://www.imperial.ac.uk/brain-sciences/study/','high',50,1),
('edinburgh-computational-neuro','edinburgh-computational-neuro-phd','爱丁堡大学机器学习与计算神经科学','University of Edinburgh Computational Neuroscience','university','Edinburgh','["机器学习","计算神经科学","信息学"]','高校','信息学、机器学习和计算神经科学交叉培养。','适合有统计、编程和认知研究背景的转型路径。','https://www.ed.ac.uk/informatics','https://study.ed.ac.uk/programmes/postgraduate-research/489-informatics-iml-machine-learning-computational-neuroscience','high',60,1),
('francis-crick','crick-phd-programme','弗朗西斯·克里克研究所','The Francis Crick Institute','research_institute','London','["生命科学","神经科学","博士培养"]','科研机构','英国大型跨学科生物医学研究机构。','博士项目和研究岗位需按年度官方批次核对。','https://www.crick.ac.uk/','https://www.crick.ac.uk/careers-study','high',70,1),
('tcd-neuroscience-institution','tcd-neuroscience','都柏林圣三一学院神经科学研究所','Trinity College Institute of Neuroscience','university','Dublin','["认知","神经影像","神经工程"]','高校','跨心理、医学、工程的爱尔兰神经科学研究平台。','关注博士、研究岗位、脑健康和认知老化方向。','https://www.tcd.ie/Neuroscience/','https://www.tcd.ie/hr/vacancies/','critical',10,1),
('ucd-psychology','ucd-psychology-research','都柏林大学心理学院','UCD School of Psychology','university','Dublin','["心理学","认知神经科学","行为科学"]','高校','研究主题包括情感、行为和认知神经科学。','适合持续跟踪研究型学位、实验室与岗位。','https://www.ucd.ie/psychology/research/','https://www.ucd.ie/workatucd/jobs/','high',20,1),
('hku-psychology','hku-research-staff-jobs','香港大学心理学系','Department of Psychology, The University of Hong Kong','university','香港','["心理学","认知神经科学","研究助理"]','高校','覆盖认知、社会、发展与临床相关心理研究。','当前已有硕士可申请科研助理，注意官方截止日。','https://psychology.hku.hk/','https://jobs.hku.hk/cw/en/Search/?category=research+staff','critical',10,1),
('cuhk-brain','cuhk-hkpfs','香港中文大学脑与认知相关研究','CUHK Brain and Cognitive Research','university','香港','["认知科学","神经科学","心理学"]','高校','通过心理、医学和工程体系开展脑与认知研究。','重点关注 HKPFS、研究型博士和跨学科实验室。','https://www.psy.cuhk.edu.hk/','https://www.gs.cuhk.edu.hk/hkpfs','high',20,1),
('hkust-neuroscience','mentor-nancy-ip','香港科技大学神经科学研究体系','HKUST Neuroscience Research','university','香港','["神经科学","脑疾病","分子机制"]','高校','以叶玉如等团队为代表的神经科学与脑疾病研究。','关注导师动态、HKPFS 和研究岗位。','https://iplab.hkust.edu.hk/','https://fytgs.hkust.edu.hk/hkpfs','critical',30,1),
('cityu-neuroscience','cityu-neuroscience-phd','香港城市大学神经科学系','Department of Neuroscience, City University of Hong Kong','university','香港','["神经科学","生物医学","研究型博士"]','高校','提供神经科学 MPhil/PhD 研究训练。','重点核对导师匹配、奖学金和申请轮次。','https://www.cityu.edu.hk/neuro/','https://www.cityu.edu.hk/neuro/edu/rpg.htm','high',40,1);
