INSERT OR IGNORE INTO sources
(id,name,source_type,coverage,organization_type,regions_json,topics_json,description,priority,url,trust_level,enabled,check_interval_hours) VALUES
('openai-careers','OpenAI Careers','listing','mixed','company','["US","UK"]','["GPT","多模态","AI Safety","研究工程"]','OpenAI 官方招聘入口，覆盖研究、工程、Residency 与早期职业机会。','critical','https://openai.com/careers/',100,1,6),
('deepmind-careers','Google DeepMind Careers','listing','mixed','company','["UK","US"]','["Gemini","强化学习","多模态","Student Researcher"]','Google DeepMind 官方招聘与学生研究项目入口。','critical','https://deepmind.google/careers/',100,1,6),
('anthropic-careers','Anthropic Careers','listing','mixed','company','["US","UK"]','["Claude","AI Safety","对齐","研究工程"]','Anthropic 官方岗位目录。','critical','https://www.anthropic.com/careers/jobs',100,1,6),
('meta-ai-careers','Meta AI Careers','listing','mixed','company','["US","UK"]','["Llama","多模态","研究科学家"]','Meta 官方招聘搜索入口，用于跟踪生成式 AI 与 FAIR 相关岗位。','high','https://www.metacareers.com/jobs/?q=AI',100,1,12),
('microsoft-ai-careers','Microsoft AI Careers','listing','mixed','company','["US","UK"]','["Copilot","Phi","研究工程"]','Microsoft 官方招聘搜索入口。','high','https://jobs.careers.microsoft.com/global/en/search?q=artificial%20intelligence',100,1,12),
('amazon-agi-careers','Amazon Science Careers','listing','mixed','company','["US","UK"]','["Nova","AGI","应用科学家"]','Amazon Science 官方科研岗位入口。','high','https://www.amazon.science/careers',100,1,12),
('xai-careers','xAI Careers','listing','mixed','company','["US","UK"]','["Grok","模型训练","研究工程"]','xAI 官方招聘目录。','high','https://x.ai/careers',100,1,12),
('mistral-careers','Mistral AI Careers','listing','mixed','company','["FR","UK"]','["Mistral","开源模型","研究工程"]','Mistral AI 官方职位目录。','high','https://jobs.lever.co/mistral/',100,1,12),
('deepseek-careers','DeepSeek 官方招聘','listing','mixed','company','["CN"]','["DeepSeek","基础模型","强化学习","研究工程"]','DeepSeek 官网链接的官方人才招聘入口。','critical','https://talent.deepseek.com/',100,1,6),
('kimi-careers','Kimi / 月之暗面招聘','listing','mixed','company','["CN"]','["Kimi","基础模型","多模态","校招"]','月之暗面官方社会招聘与校园招聘入口。','critical','https://careers.kimi.com/',100,1,6),
('zhipu-careers','智谱 GLM 官方人才入口','listing','mixed','company','["CN"]','["GLM","多模态","智能体","研究工程"]','智谱官方站点人才信息入口；在专用招聘页稳定前先监测官方站变化。','high','https://www.zhipuai.cn/',100,1,12),
('alibaba-ai-careers','阿里巴巴 AI 人才招聘','listing','mixed','company','["CN"]','["通义千问","Qwen","达摩院","校招"]','阿里巴巴官方人才招聘入口。','critical','https://talent.alibaba.com/',100,1,6),
('tencent-ai-careers','腾讯 AI 人才招聘','listing','mixed','company','["CN"]','["混元","Hunyuan","腾讯 AI Lab","校招"]','腾讯官方招聘入口。','critical','https://careers.tencent.com/',100,1,6),
('bytedance-seed-careers','字节跳动 Seed 大模型人才招聘','listing','campus','company','["CN","UK"]','["豆包","Seed","基础模型","AI Safety","校招"]','字节跳动官方前沿技术人才校招与 Seed 大模型机会入口。','critical','https://jobs.bytedance.com/campus/page-6272Gc',100,1,6),
('baidu-ai-careers','百度 AI 人才招聘','listing','mixed','company','["CN"]','["文心","ERNIE","深度学习","校招"]','百度官方招聘岗位目录。','high','https://talent.baidu.com/jobs/list',100,1,12),
('huawei-ai-careers','华为 AI 人才招聘','listing','mixed','company','["CN","UK"]','["盘古","昇腾","诺亚方舟实验室","校招"]','华为官方招聘入口。','high','https://career.huawei.com/',100,1,12),
('minimax-official','MiniMax 官方人才观察','listing','mixed','company','["CN"]','["MiniMax","多模态","语音","智能体"]','MiniMax 官方站点；用于发现公开人才入口和招聘变化。','high','https://www.minimaxi.com/',100,1,12),
('stepfun-official','阶跃星辰官方人才观察','listing','mixed','company','["CN"]','["Step","多模态","基础模型"]','阶跃星辰官方站点；用于发现公开人才入口和招聘变化。','high','https://www.stepfun.com/',100,1,12);
--> statement-breakpoint
INSERT OR IGNORE INTO institutions
(id,source_id,name,name_en,institution_type,city,topics_json,mark,summary,note,url,opportunity_url,priority,sort_order,published) VALUES
('company-openai','openai-careers','OpenAI','OpenAI','company','San Francisco','["GPT","多模态","AI Safety","研究工程"]','全球头部','基础模型、推理、多模态、对齐和产品研究。','官方招聘页与具体岗位分开呈现，页面出现不等于岗位适合所有学历背景。','https://openai.com/','https://openai.com/careers/','critical',10,1),
('company-deepmind','deepmind-careers','Google DeepMind','Google DeepMind','company','London','["Gemini","强化学习","Student Researcher","AI for Science"]','英国重点','Gemini、强化学习、AI for Science 与基础研究。','伦敦为重点研究中心，并提供单独的 Student Researcher 项目入口。','https://deepmind.google/','https://deepmind.google/careers/','critical',20,1),
('company-anthropic','anthropic-careers','Anthropic','Anthropic','company','San Francisco / London','["Claude","AI Safety","对齐","研究工程"]','全球头部','聚焦可靠、可解释和可控的前沿模型。','官方岗位目录包含美国和伦敦机会，资格与办公地点逐岗核对。','https://www.anthropic.com/','https://www.anthropic.com/careers/jobs','critical',30,1),
('company-meta-ai','meta-ai-careers','Meta AI / FAIR','Meta AI / FAIR','company','Global','["Llama","多模态","研究科学家"]','全球头部','Llama 与 FAIR 基础研究生态。','使用官方职位搜索跟踪，结果数量和地点会动态变化。','https://ai.meta.com/','https://www.metacareers.com/jobs/?q=AI','high',40,1),
('company-microsoft-ai','microsoft-ai-careers','Microsoft AI','Microsoft AI','company','Global','["Copilot","Phi","研究工程"]','全球头部','基础模型、智能体、Copilot 与 Microsoft Research 生态。','官方职位搜索动态更新。','https://www.microsoft.ai/','https://jobs.careers.microsoft.com/global/en/search?q=artificial%20intelligence','high',50,1),
('company-amazon-agi','amazon-agi-careers','Amazon AGI / Science','Amazon AGI / Science','company','Global','["Nova","AGI","应用科学家"]','全球头部','基础模型、应用科学与大规模系统。','重点查看 Applied Scientist、Research Scientist 与实习岗位。','https://www.amazon.science/','https://www.amazon.science/careers','high',60,1),
('company-xai','xai-careers','xAI','xAI','company','San Francisco / London','["Grok","模型训练","研究工程"]','全球头部','基础模型、推理和模型训练。','官方目录动态变化，伦敦岗位单独标记地点。','https://x.ai/','https://x.ai/careers','high',70,1),
('company-mistral','mistral-careers','Mistral AI','Mistral AI','company','Paris / London','["Mistral","开源模型","研究工程"]','欧洲重点','欧洲基础模型与开放模型生态。','巴黎为核心，同时跟踪英国和其他地区岗位。','https://mistral.ai/','https://jobs.lever.co/mistral/','high',80,1),
('company-deepseek','deepseek-careers','DeepSeek 深度求索','DeepSeek','company','杭州','["DeepSeek","基础模型","强化学习","研究工程"]','中国头部','基础模型、推理、代码和强化学习。','只链接 deepseek.com 指向的人才官方域名。','https://deepseek.com/','https://talent.deepseek.com/','critical',110,1),
('company-kimi','kimi-careers','Kimi / 月之暗面','Moonshot AI / Kimi','company','北京','["Kimi","基础模型","多模态","校招"]','中国头部','长上下文、推理、多模态与通用智能。','官方招聘站提供校园招聘和 Build Your Own Job。','https://www.moonshot.ai/','https://careers.kimi.com/','critical',120,1),
('company-zhipu','zhipu-careers','智谱 AI / GLM','Zhipu AI / GLM','company','北京','["GLM","多模态","智能体"]','中国头部','GLM 基础模型、多模态与智能体。','专用招聘入口尚待稳定核验，当前先监测官方站，不虚构具体岗位。','https://www.zhipuai.cn/','https://www.zhipuai.cn/','high',130,1),
('company-alibaba-qwen','alibaba-ai-careers','阿里巴巴 / 通义千问','Alibaba / Qwen','company','杭州 / 北京','["通义千问","Qwen","达摩院","校招"]','中国头部','Qwen 基础模型、达摩院研究和大模型产品。','通过阿里官方人才平台持续跟踪。','https://www.alibabagroup.com/','https://talent.alibaba.com/','critical',140,1),
('company-tencent-hunyuan','tencent-ai-careers','腾讯 / 混元','Tencent / Hunyuan','company','深圳 / 北京','["混元","Hunyuan","腾讯 AI Lab"]','中国头部','混元基础模型、腾讯 AI Lab 与产业应用。','深圳与北京均为重点地点。','https://www.tencent.com/','https://careers.tencent.com/','critical',150,1),
('company-bytedance-seed','bytedance-seed-careers','字节跳动 Seed / 豆包','ByteDance Seed / Doubao','company','北京 / 深圳 / London','["豆包","Seed","基础模型","AI Safety","AI for Science"]','中国头部','Seed 基础模型、豆包、多模态、AI Safety、AI Coding 与 AI for Science。','官方前沿技术人才项目明确覆盖 2027 届及以后学生。','https://team.doubao.com/','https://jobs.bytedance.com/campus/page-6272Gc','critical',160,1),
('company-baidu-ernie','baidu-ai-careers','百度 / 文心','Baidu / ERNIE','company','北京 / 深圳','["文心","ERNIE","深度学习"]','中国头部','文心基础模型、飞桨与产业 AI。','通过百度官方人才目录跟踪。','https://www.baidu.com/','https://talent.baidu.com/jobs/list','high',170,1),
('company-huawei-pangu','huawei-ai-careers','华为 / 盘古','Huawei / Pangu','company','深圳 / London','["盘古","昇腾","诺亚方舟实验室"]','中国头部','盘古、昇腾和诺亚方舟实验室研究生态。','同时关注深圳与英国研究岗位。','https://www.huawei.com/','https://career.huawei.com/','high',180,1),
('company-minimax','minimax-official','MiniMax','MiniMax','company','上海','["MiniMax","多模态","语音","智能体"]','中国重点','多模态、语音、视频和智能体。','官方招聘入口待自动发现和核验，当前不展示未证实岗位。','https://www.minimaxi.com/','https://www.minimaxi.com/','high',190,1),
('company-stepfun','stepfun-official','阶跃星辰','StepFun','company','上海','["Step","多模态","基础模型"]','中国重点','多模态基础模型与智能终端生态。','官方招聘入口待自动发现和核验，当前不展示未证实岗位。','https://www.stepfun.com/','https://www.stepfun.com/','high',200,1);
--> statement-breakpoint
INSERT OR IGNORE INTO opportunities
(id,source_id,name,org,kind,status,fit,location,deadline,deadline_status,masters_eligible,eligibility_details,phd_bridge_details,why,action,tags_json,url,published,source_verified_at) VALUES
('bytedance-frontier-talent-2027','bytedance-seed-careers','字节跳动前沿技术领域人才校招','字节跳动 Seed / 豆包','校招','立即行动','匹配','北京 / 深圳 / London','面向 2027 届及以后｜岗位滚动更新','rolling',1,'面向全球优秀技术人才，具体学历、专业与毕业时间按岗位说明核对。',NULL,'官方项目覆盖 Seed 基础大模型、AI Safety、AI Coding、具身智能和 AI for Science。','进入官方项目页筛选 Seed、大模型、AI Safety、AI for Science 与目标城市岗位。','["字节跳动","豆包","Seed","2027届","大模型"]','https://jobs.bytedance.com/campus/page-6272Gc',1,'2026-08-01T00:00:00.000Z'),
('google-deepmind-student-researcher-watch','deepmind-careers','Google DeepMind Student Researcher','Google DeepMind','实习','持续关注','匹配','London / Global','按官方项目批次开放','unknown',1,'面向在读本科、硕士或博士；具体地点、学籍与申请窗口以官方项目页为准。',NULL,'可接触 Google DeepMind 的前沿研究项目，是硕士阶段进入研究团队的重要路径。','查看 Student Researcher 官方页并按地点和开放批次准备简历、研究经历与代码证据。','["Google DeepMind","Student Researcher","Gemini","研究实习"]','https://deepmind.google/student-researcher-program/',1,'2026-08-01T00:00:00.000Z'),
('openai-emerging-talent-watch','openai-careers','OpenAI Emerging Talent / Residency','OpenAI','研究岗位','持续关注','转型匹配','San Francisco / Global','按官方项目批次开放','unknown',1,'不同项目面向早期职业候选人或跨领域研究者，逐项目核对资格。',NULL,'官方 careers 页面集中展示早期职业和 Residency 路径。','订阅官方入口，并把研究、工程与可复现项目证据对应到具体岗位要求。','["OpenAI","Emerging Talent","Residency","研究工程"]','https://openai.com/careers/',1,'2026-08-01T00:00:00.000Z');
