-- Early-career focus lines: UK top-university research roles, UK employers, and Hong Kong universities/companies.
INSERT OR IGNORE INTO sources
(id,name,source_type,coverage,organization_type,regions_json,topics_json,description,priority,url,trust_level,enabled,check_interval_hours) VALUES
('hku-career-opportunities','香港大学 Career Opportunities','listing','campus','university','["HK"]','["校招重点","高校校招","研究岗位","学院","导师","香港"]','香港大学官方职位目录，跟踪学院、研究中心、导师课题组与行政专业岗位；具体资格和截止日逐项核对。','high','https://jobs.hku.hk/cw/en/j',100,1,12),
('hkust-graduate-jobs-portal','HKUST Graduate Jobs Portal','listing','campus','university','["HK"]','["校招重点","高校校招","毕业生","研究助理","香港"]','香港科技大学商学院建立的毕业生就业门户，提供香港本科生与应届毕业生岗位市场和职位趋势入口。','high','https://graduatejobsportal.hkust.edu.hk/',100,1,12),
('cuhk-career-opportunities','香港中文大学工作机会','listing','campus','university','["HK"]','["校招重点","高校校招","研究助理","学院","香港"]','香港中文大学人力资源处官方工作机会入口，覆盖教研、专业、行政、技术员和研究职位。','high','https://www.hro.cuhk.edu.hk/zh-cn/career/career-opportunities',100,1,12),
('hkstp-talent-early-careers','HKSTP Careers and Talent','listing','campus','company','["HK"]','["校招重点","香港企业","科技企业","实习","研究岗位"]','香港科技园官方人才入口，覆盖 HKSTP 自身岗位、实习与园区科技企业人才机会。','high','https://www.hkstp.org/talent',100,1,12);
--> statement-breakpoint
UPDATE sources SET coverage='campus', regions_json='["HK","UK"]', topics_json='["校招重点","香港企业","英国企业","Graduate","Student Work Placement","银行"]', description='汇丰官方学生与毕业生项目目录，可按 Hong Kong SAR、United Kingdom、Graduate、Internship 和 Student Work Placement 筛选。', priority='high', check_interval_hours=12 WHERE id='hsbc-graduate-programmes';
--> statement-breakpoint
UPDATE sources SET coverage='mixed', topics_json='["校招重点","英国顶级高校","科研助理","实验室","课题组","学院","导师","实验心理学","神经科学"]', description='牛津大学官方 Jobs 入口；重点跟踪实验心理学、神经科学、脑科学、AI for Healthcare 及具体实验室/课题组/学院 Research Assistant、Research Technician 等岗位。', priority='critical', check_interval_hours=6 WHERE id='oxford-research-jobs';
--> statement-breakpoint
UPDATE sources SET coverage='mixed', topics_json='["校招重点","英国顶级高校","科研助理","实验室","课题组","学院","导师","心理学","认知神经科学"]', description='剑桥大学官方 Job Opportunities 入口；重点跟踪 Psychology、MRC CBU、Clinical Neurosciences、学院和实验室的 Research Assistant / Technician 岗位。', priority='critical', check_interval_hours=6 WHERE id='cambridge-current-jobs';
--> statement-breakpoint
UPDATE sources SET coverage='mixed', topics_json='["校招重点","英国顶级高校","科研助理","实验室","课题组","学院","导师","心理学","脑科学"]' WHERE id='ucl-current-jobs';
--> statement-breakpoint
UPDATE opportunities SET tags_json='["2027校招专题","校招重点","赛道:英国顶级高校研究岗位","Oxford","实验室","课题组","学院","导师","科研助理","英国"]' WHERE id='oxford-research-assistant-watch';
--> statement-breakpoint
UPDATE opportunities SET tags_json='["2027校招专题","校招重点","赛道:英国顶级高校研究岗位","Cambridge","实验室","课题组","学院","导师","科研助理","英国"]' WHERE id='cambridge-research-assistant-watch';
--> statement-breakpoint
UPDATE opportunities SET tags_json='["2027校招专题","校招重点","赛道:英国顶级高校研究岗位","UCL","实验室","课题组","学院","导师","科研助理","英国"]' WHERE id='ucl-research-assistant-watch';
--> statement-breakpoint
UPDATE opportunities SET tags_json=REPLACE(tags_json, '"赛道:国外大厂"', '"赛道:国外大厂","赛道:英国企业校招"') WHERE id IN ('microsoft-uk-early-career-watch','amazon-uk-university-watch','apple-uk-ml-student-watch','nvidia-uk-cn-new-grad-watch','arm-uk-2027-graduate-watch','google-deepmind-student-researcher-watch');
--> statement-breakpoint
INSERT OR IGNORE INTO opportunities
(id,source_id,name,org,kind,status,fit,location,deadline,deadline_status,opens_at,masters_eligible,eligibility_details,phd_bridge_details,why,action,tags_json,url,published,source_verified_at) VALUES
('oxford-top-university-research-focus','oxford-research-jobs','Oxford 顶级高校实验室 / 课题组 Research Assistant 重点跟踪','牛津大学','研究岗位','持续关注','高度匹配','Oxford','官方岗位库滚动更新｜逐岗核对截止时间','rolling',NULL,1,'Research Assistant、Research Technician 和项目岗位的学位、学科、工作许可与合同期逐岗核对。','英国实验室研究经历可积累方法训练、论文协作和导师推荐，但不等于自动获得牛津博士录取。','把牛津大学 Jobs 作为实验心理学、神经科学、脑健康、AI for Healthcare 及具体学院/课题组的长期入口。','每周用 Research Assistant、Psychology、Neuroscience、AI、Laboratory 组合检索；保存具体实验室、PI、截止日和签证信息。','["2027校招专题","校招重点","赛道:英国顶级高校研究岗位","Oxford","实验室","课题组","学院","导师"]','https://www.ox.ac.uk/about/jobs',1,NULL),
('cambridge-top-university-research-focus','cambridge-current-jobs','Cambridge 顶级高校实验室 / 课题组 Research Assistant 重点跟踪','剑桥大学','研究岗位','持续关注','高度匹配','Cambridge','官方岗位库滚动更新｜逐岗核对截止时间','rolling',NULL,1,'Research Assistant 多数逐岗要求本科或硕士背景；Research Associate 常有博士要求，必须区分职级。','可在 Psychology、MRC CBU、Clinical Neurosciences、学院和实验室积累研究成果与推荐信。','剑桥官方职位库覆盖学院、附属机构、实验室和课题组，是实验心理学与认知神经研究岗位的重点入口。','组合检索 Research Assistant、Psychology、Cognition、Neuroscience、Laboratory；记录 PI、学院、合同期和工作许可。','["2027校招专题","校招重点","赛道:英国顶级高校研究岗位","Cambridge","实验室","课题组","学院","导师"]','https://www.jobs.cam.ac.uk/',1,NULL),
('ucl-top-university-research-focus','ucl-current-jobs','UCL Brain Sciences / Psychology Research Assistant 重点跟踪','UCL','研究岗位','持续关注','高度匹配','London','官方岗位库滚动更新｜逐岗核对截止时间','rolling',NULL,1,'岗位的学历、研究经验、工作许可和合同期逐项核对。','适合从实验心理学向脑科学、神经影像、健康心理与行为研究过渡。','重点覆盖 Faculty of Brain Sciences、Psychology and Language Sciences、影像神经科学实验室和具体导师课题组。','每周筛选 Research Assistant、Psychology、Brain Sciences、Neuroscience，并追踪导师与实验室页面。','["2027校招专题","校招重点","赛道:英国顶级高校研究岗位","UCL","实验室","课题组","学院","导师"]','https://www.ucl.ac.uk/work-at-ucl/search-ucl-jobs',1,NULL),
('hku-early-career-focus','hku-career-opportunities','香港大学学院 / 研究中心 / 导师课题组机会','香港大学','研究岗位','持续关注','高度匹配','香港','官方职位目录滚动更新｜逐岗核对截止时间','rolling',NULL,1,'研究助理、研究中心、学院和专业岗位的学历、语言、工作许可与截止日逐岗核对。','可积累香港高校研究项目、数据分析、受试者研究和推荐信经历。','将 HKU Career Opportunities 与已有 Research Staff / Psychology 来源合并观察，覆盖学院、研究中心和导师课题组。','优先筛选 Research Assistant、Research Staff、Psychology、Neuroscience、Behavioural Science；同步查看具体学院和 PI 页面。','["2027校招专题","校招重点","赛道:香港高校校招","香港大学","学院","研究中心","导师"]','https://jobs.hku.hk/cw/en/j',1,NULL),
('hkust-early-career-focus','hkust-graduate-jobs-portal','香港科技大学毕业生 / 研究助理机会','香港科技大学','校招','持续关注','匹配','香港','毕业生岗位与研究助理入口滚动更新','rolling',NULL,1,'职位趋势门户不等于每个岗位已开放；需回到雇主或 HKUST 官方职位页确认资格、截止日和工作许可。','可作为香港科技、AI、数据、研究助理与毕业生岗位的入口补充。','HKUST Graduate Jobs Portal 聚合香港本科生与应届毕业生市场，并可观察 Research Assistant / Technicians、R&D 和 Management Trainee 等类别。','优先筛选 Research Assistant、R&D、AI、Data、Graduate；对具体岗位回到雇主官方页面核验。','["2027校招专题","校招重点","赛道:香港高校校招","香港科技大学","毕业生","研究助理"]','https://graduatejobsportal.hkust.edu.hk/',1,NULL),
('cuhk-early-career-focus','cuhk-career-opportunities','香港中文大学学院 / 研究岗位机会','香港中文大学','研究岗位','持续关注','匹配','香港','教研、专业、行政与研究职位滚动更新','rolling',NULL,1,'CUHK HR 官方目录提供入口；具体学院、研究中心和课题组岗位以职位页为准。','可关注社会科学、心理学、AI、数据与跨学科研究助理机会。','通过 CUHK HR 与学院/研究中心页面跟踪 Research Assistant、Junior Research Assistant、Student Helper 及专业岗位。','每周检查 CUHK HR、学院 Job Vacancies 和导师课题组页面，记录岗位是否接受硕士和非本地申请者。','["2027校招专题","校招重点","赛道:香港高校校招","香港中文大学","学院","研究助理","导师"]','https://www.hro.cuhk.edu.hk/zh-cn/career/career-opportunities',1,NULL),
('hsbc-hk-early-career-focus','hsbc-graduate-programmes','HSBC 香港 Student Work Placement / Graduate','HSBC','校招','持续关注','转型匹配','香港','按官方项目批次开放｜逐项核对截止时间','unknown',NULL,1,'香港项目的学位、语言、毕业年份和工作许可要求逐项核对；项目开放状态以官方目录为准。',NULL,'香港企业校招中优先关注 HSBC Student Work Placement、Graduate 和 Corporate / Technology 相关项目。','按 Hong Kong SAR、Graduate、Internship、Student Work Placement 筛选；保存 opening/closing date 和项目类型。','["2027校招专题","校招重点","赛道:香港企业校招","HSBC","香港","Graduate"]','https://www.hsbc.com/careers/students-and-graduates/find-a-programme',1,NULL),
('hkstp-early-career-focus','hkstp-talent-early-careers','HKSTP 科技园企业 / 实习 / 早期职业机会','香港科技园','校招','持续关注','匹配','香港','官方人才入口与园区企业机会滚动更新','rolling',NULL,1,'HKSTP 入口包含自身岗位与园区企业机会；具体雇主、岗位、毕业资格与工作许可逐项核对。',NULL,'香港科技园连接大量科技企业，适合关注 AI、健康科技、数据、研发和产品早期职业机会。','先查看 HKSTP Careers，再进入园区企业招聘页；不把人才生态介绍直接视为已开放职位。','["2027校招专题","校招重点","赛道:香港企业校招","HKSTP","科技企业","香港"]','https://www.hkstp.org/talent',1,NULL);
--> statement-breakpoint
PRAGMA optimize;
