import type { Metadata } from "next";
import Link from "next/link";
import styles from "../../documentation.module.css";
export const metadata: Metadata={title:"P2 学术情报雷达 PRD｜BRAIN / 27",description:"导师、论文、顶会、项目、议题与科研政策跟踪的产品需求文档。"};
export default function AcademicPrd(){return <main className={styles.page}><nav className={styles.nav}><Link href="/" className={styles.brand}>BRAIN / 27</Link><div className={styles.navLinks}><Link href="/conferences">学术顶会</Link><Link href="/researchers">导师雷达</Link><Link href="/papers">最新论文</Link><Link href="/policies">科研政策</Link><Link href="/paper-sources">论文数据库</Link><Link href="/prd">总 PRD</Link></div></nav><header className={styles.hero}><div><p className={styles.eyebrow}>PRODUCT REQUIREMENTS · P2</p><h1>学术情报雷达<br/><span>从机会扩展到人、论文与顶会</span></h1><p className={styles.lead}>P2 把导师、论文、学术顶会、研究项目、热点议题和全球科研政策连接为可追溯的证据网络，并统一进入 Cron、搜索、日历、报告和知识图谱。</p></div><div className={styles.heroMeta}><span>PRD VERSION</span><strong>0.13.0</strong><p>2026-08-02 · P2.1—P2.5.1 已交付</p></div></header><div className={styles.content}>
<section className={styles.section}><div className={styles.sectionHead}><h2>产品目标</h2><p>找到“谁在做什么、最近发生了什么、哪些会议需要现在行动”，同时保留事实与推断的边界。</p></div><div className={styles.cardGrid}><article className={`${styles.card} ${styles.cardDone}`}><p>01 / P2.1</p><h3>导师雷达</h3><p>官方主页、机构、主题、方法、申请价值与最近核验时间。</p></article><article className={`${styles.card} ${styles.cardDone}`}><p>02 / P2.2</p><h3>最新论文</h3><p>6 个数据库近 18 个月发现，多标识符去重、作者与主题匹配。</p></article><article className={`${styles.card} ${styles.cardDone}`}><p>03 / P2.3—P2.5</p><h3>项目 / 议题 / 政策</h3><p>独立政策管线、历史版本、候选隔离及多页面集成。</p></article><article className={`${styles.card} ${styles.cardDone}`}><p>04 / P2.5.1</p><h3>学术顶会</h3><p>13 个心理学、脑科学和 AI 会议；20 个官方节点进入统一日历。</p></article></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>核心规则</h2><p>系统宁可少收，也不把同名作者或主题噪声伪装成确定事实。</p></div><div className={styles.requirements}><article className={styles.requirement}><h3>导师不是排名</h3><ul><li>优先级表示用户匹配和检查频率</li><li>招生状态必须有官方证据</li><li>不批量收集私人联系方式</li></ul></article><article className={styles.requirement}><h3>论文分层</h3><ul><li>DOI 优先去重</li><li>作者名与主题双重筛选</li><li>未核验身份只产生候选</li></ul></article><article className={styles.requirement}><h3>失败隔离</h3><ul><li>外部 API 失败不清空历史</li><li>单导师失败不终止整批</li><li>运行和实体事件均可追溯</li></ul></article><article className={styles.requirement}><h3>自动边界</h3><ul><li>不自动发邮件或申请</li><li>不绕过访问控制</li><li>撤稿和更正必须显式保留</li></ul></article></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>顶会运行流程</h2><p>顶会与科研政策使用独立错峰 Cron；发现变化并保存证据，不让未核验文本直接改写日历。</p></div><div className={styles.flow}><article className={styles.flowStep}><b>01</b><h3>官网种子</h3><p>核验会议、类型和官方入口。</p></article><article className={styles.flowStep}><b>02</b><h3>日期分层</h3><p>精确、月份确认与 TBA 分开。</p></article><article className={styles.flowStep}><b>03</b><h3>Cron 巡检</h3><p>四路并发、超时与正文上限。</p></article><article className={styles.flowStep}><b>04</b><h3>版本留证</h3><p>官网变化写入版本历史。</p></article><article className={styles.flowStep}><b>05</b><h3>日历行动</h3><p>只发布已确认的精确节点。</p></article></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>验收条件</h2><p>数据库、接口、页面、定时任务和证据日志同时通过才可发布。</p></div><ul className={styles.checklist}><li><span>01</span><div><strong>16 位导师及官方来源进入 D1</strong><br/><small>覆盖英国、中国内地、中国香港和全球代表团队。</small></div><span className={styles.tag}>已开发</span></li><li><span>02</span><div><strong>论文发现有限、幂等、可解释</strong><br/><small>请求超时、条数上限、作者/主题阈值和 DOI 去重。</small></div><span className={styles.tag}>已开发</span></li><li><span>03</span><div><strong>桌面与手机可读</strong><br/><small>筛选区与卡片在窄屏变为单列。</small></div><span className={styles.tagPending}>待验收</span></li></ul></section>
</div><footer className={styles.footer}><span>BRAIN / 27 · Academic PRD v0.13</span><p>下一阶段：P2.6 统一审核工作台与通知摘要。</p></footer></main>}
