import type { Metadata } from "next";
import Link from "next/link";
import styles from "../../documentation.module.css";
export const metadata: Metadata={title:"P2 学术情报雷达 PRD｜BRAIN / 27",description:"导师、论文、项目、议题与科研政策跟踪的产品需求文档。"};
export default function AcademicPrd(){return <main className={styles.page}><nav className={styles.nav}><Link href="/" className={styles.brand}>BRAIN / 27</Link><div className={styles.navLinks}><Link href="/researchers">导师雷达</Link><Link href="/papers">最新论文</Link><Link href="/paper-sources">论文数据库</Link><Link href="/prd">总 PRD</Link></div></nav><header className={styles.hero}><div><p className={styles.eyebrow}>PRODUCT REQUIREMENTS · P2</p><h1>学术情报雷达<br/><span>从机会扩展到人、论文与政策</span></h1><p className={styles.lead}>P2 把导师主页、外部学术身份、近期论文和后续研究项目连接为可追溯的证据网络。本期先交付导师与论文。</p></div><div className={styles.heroMeta}><span>PRD VERSION</span><strong>0.2.0</strong><p>2026-08-01 · 论文多数据库接入</p></div></header><div className={styles.content}>
<section className={styles.section}><div className={styles.sectionHead}><h2>产品目标</h2><p>找到“谁在做什么、最近发生了什么、是否值得现在联系”，同时保留事实与推断的边界。</p></div><div className={`${styles.cardGrid} ${styles.requirements}`}><article className={`${styles.card} ${styles.cardDone}`}><p>01 / P2.1</p><h3>导师雷达</h3><p>首批 16 位；官方主页、机构、主题、方法、申请价值与最近核验时间。</p></article><article className={`${styles.card} ${styles.cardDone}`}><p>02 / P2.2</p><h3>最新论文</h3><p>Crossref 近 18 个月发现、DOI 去重、作者与主题匹配、候选核验标签。</p></article><article className={`${styles.card} ${styles.cardNext}`}><p>03 / NEXT</p><h3>项目 / 议题 / 政策</h3><p>研究项目、经费合作、会议主题和全球科研政策变化。</p></article></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>核心规则</h2><p>系统宁可少收，也不把同名作者或主题噪声伪装成确定事实。</p></div><div className={styles.requirements}><article className={styles.requirement}><h3>导师不是排名</h3><ul><li>优先级表示用户匹配和检查频率</li><li>招生状态必须有官方证据</li><li>不批量收集私人联系方式</li></ul></article><article className={styles.requirement}><h3>论文分层</h3><ul><li>DOI 优先去重</li><li>作者名与主题双重筛选</li><li>未核验身份只产生候选</li></ul></article><article className={styles.requirement}><h3>失败隔离</h3><ul><li>外部 API 失败不清空历史</li><li>单导师失败不终止整批</li><li>运行和实体事件均可追溯</li></ul></article><article className={styles.requirement}><h3>自动边界</h3><ul><li>不自动发邮件或申请</li><li>不绕过访问控制</li><li>撤稿和更正必须显式保留</li></ul></article></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>运行流程</h2><p>同一个 Cloudflare Cron 触发职业来源与学术论文两条彼此隔离的管线。</p></div><div className={styles.flow}><article className={styles.flowStep}><b>01</b><h3>Cron</h3><p>每日 4 次触发。</p></article><article className={styles.flowStep}><b>02</b><h3>身份查询</h3><p>读取导师与 Crossref 查询身份。</p></article><article className={styles.flowStep}><b>03</b><h3>有限发现</h3><p>18 个月、每人最多 5 条。</p></article><article className={styles.flowStep}><b>04</b><h3>匹配去重</h3><p>作者、主题、DOI 与置信度。</p></article><article className={styles.flowStep}><b>05</b><h3>候选展示</h3><p>透明标记，等待进一步核验。</p></article></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>验收条件</h2><p>数据库、接口、页面、定时任务和证据日志同时通过才可发布。</p></div><ul className={styles.checklist}><li><span>01</span><div><strong>16 位导师及官方来源进入 D1</strong><br/><small>覆盖英国、中国内地、中国香港和全球代表团队。</small></div><span className={styles.tag}>已开发</span></li><li><span>02</span><div><strong>论文发现有限、幂等、可解释</strong><br/><small>请求超时、条数上限、作者/主题阈值和 DOI 去重。</small></div><span className={styles.tag}>已开发</span></li><li><span>03</span><div><strong>桌面与手机可读</strong><br/><small>筛选区与卡片在窄屏变为单列。</small></div><span className={styles.tagPending}>待验收</span></li></ul></section>
</div><footer className={styles.footer}><span>BRAIN / 27 · Academic PRD v0.1</span><p>下一阶段：研究项目、热门议题与科研政策。</p></footer></main>}
