type ReportDatabase={prepare:(sql:string)=>{bind:(...values:unknown[])=>{first:<T>()=>Promise<T|null>;all:<T>()=>Promise<{results:T[]}>;run:()=>Promise<unknown>}}};
type CountRow={new_opportunities:number;new_sources:number;new_papers:number;new_policies:number;new_projects:number;source_changes:number;source_failures:number;source_runs:number;academic_runs:number;policy_runs:number};
type NameRow={name:string};export type ReportPeriod="daily"|"weekly"|"monthly";
export async function refreshIntelligenceReports(database:ReportDatabase,now=new Date()){const today=utcDate(now),weekStart=startOfWeek(today),monthStart=`${today.slice(0,7)}-01`,periods=[{type:"daily"as const,start:today,end:today},{type:"weekly"as const,start:weekStart,end:addDays(weekStart,6)},{type:"monthly"as const,start:monthStart,end:addDays(addMonths(monthStart,1),-1)}],reports=[];for(const p of periods)reports.push(await refreshPeriod(database,p.type,p.start,p.end,now));console.log(JSON.stringify({event:"radar.reports.refreshed",date:today,reports:reports.map(x=>({id:x.id,type:x.periodType,newOpportunities:x.newOpportunities,newPapers:x.newPapers,newPolicies:x.newPolicies,newProjects:x.newProjects}))}));return reports}
async function refreshPeriod(database:ReportDatabase,periodType:ReportPeriod,periodStart:string,periodEnd:string,now:Date){const from=`${periodStart}T00:00:00.000Z`,until=`${addDays(periodEnd,1)}T00:00:00.000Z`,counts=await database.prepare(`SELECT
(SELECT COUNT(*) FROM opportunities WHERE published=1 AND created_at>=? AND created_at<?) new_opportunities,
(SELECT COUNT(*) FROM sources WHERE created_at>=? AND created_at<?) new_sources,
(SELECT COUNT(*) FROM papers WHERE created_at>=? AND created_at<?) new_papers,
(SELECT COUNT(*) FROM research_policies WHERE published=1 AND review_status='verified' AND created_at>=? AND created_at<?) new_policies,
(SELECT COUNT(*) FROM research_projects WHERE published=1 AND created_at>=? AND created_at<?) new_projects,
(SELECT COUNT(*) FROM source_check_logs WHERE changed=1 AND checked_at>=? AND checked_at<?) source_changes,
(SELECT COUNT(*) FROM source_check_logs WHERE ok=0 AND checked_at>=? AND checked_at<?) source_failures,
(SELECT COUNT(*) FROM sync_runs WHERE started_at>=? AND started_at<?) source_runs,
(SELECT COUNT(*) FROM academic_sync_runs WHERE started_at>=? AND started_at<?) academic_runs,
(SELECT COUNT(*) FROM policy_sync_runs WHERE started_at>=? AND started_at<?) policy_runs`).bind(from,until,from,until,from,until,from,until,from,until,from,until,from,until,from,until,from,until,from,until).first<CountRow>();if(!counts)throw new Error("report count query returned no row");
const[opportunities,sources,papers,policies,projects]=await Promise.all([database.prepare(`SELECT name FROM opportunities WHERE published=1 AND created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 8`).bind(from,until).all<NameRow>(),database.prepare(`SELECT name FROM sources WHERE created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 8`).bind(from,until).all<NameRow>(),database.prepare(`SELECT COALESCE(title_zh,title) name FROM papers WHERE created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 8`).bind(from,until).all<NameRow>(),database.prepare(`SELECT title name FROM research_policies WHERE published=1 AND review_status='verified' AND created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 8`).bind(from,until).all<NameRow>(),database.prepare(`SELECT name FROM research_projects WHERE published=1 AND created_at>=? AND created_at<? ORDER BY created_at DESC LIMIT 8`).bind(from,until).all<NameRow>()]);
const label=periodType==="daily"?"日报":periodType==="weekly"?"周报":"月报",summary=`${label}：新增机会 ${counts.new_opportunities} 个、信息源 ${counts.new_sources} 个、论文 ${counts.new_papers} 篇、科研政策 ${counts.new_policies} 项、研究项目 ${counts.new_projects} 项；完成来源巡检 ${counts.source_runs} 轮、论文同步 ${counts.academic_runs} 轮、政策同步 ${counts.policy_runs} 轮，发现 ${counts.source_changes} 个来源变化，${counts.source_failures} 次来源检查失败。`,id=`${periodType}:${periodStart}`,generatedAt=now.toISOString(),highlights={opportunities:opportunities.results.map(x=>x.name),sources:sources.results.map(x=>x.name),papers:papers.results.map(x=>x.name),policies:policies.results.map(x=>x.name),projects:projects.results.map(x=>x.name)};
await database.prepare(`INSERT INTO intelligence_reports (id,period_type,period_start,period_end,new_opportunities,new_sources,new_papers,new_policies,new_projects,source_changes,source_failures,source_runs,academic_runs,policy_runs,summary,highlights_json,generated_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(period_type,period_start) DO UPDATE SET period_end=excluded.period_end,new_opportunities=excluded.new_opportunities,new_sources=excluded.new_sources,new_papers=excluded.new_papers,new_policies=excluded.new_policies,new_projects=excluded.new_projects,source_changes=excluded.source_changes,source_failures=excluded.source_failures,source_runs=excluded.source_runs,academic_runs=excluded.academic_runs,policy_runs=excluded.policy_runs,summary=excluded.summary,highlights_json=excluded.highlights_json,generated_at=excluded.generated_at,updated_at=excluded.updated_at`).bind(id,periodType,periodStart,periodEnd,counts.new_opportunities,counts.new_sources,counts.new_papers,counts.new_policies,counts.new_projects,counts.source_changes,counts.source_failures,counts.source_runs,counts.academic_runs,counts.policy_runs,summary,JSON.stringify(highlights),generatedAt,generatedAt).run();return{id,periodType,periodStart,periodEnd,newOpportunities:counts.new_opportunities,newSources:counts.new_sources,newPapers:counts.new_papers,newPolicies:counts.new_policies,newProjects:counts.new_projects,sourceChanges:counts.source_changes,sourceFailures:counts.source_failures,sourceRuns:counts.source_runs,academicRuns:counts.academic_runs,policyRuns:counts.policy_runs,summary,highlights,generatedAt}}
function utcDate(v:Date){return v.toISOString().slice(0,10)}function startOfWeek(d:string){const v=new Date(`${d}T00:00:00.000Z`),day=v.getUTCDay()||7;v.setUTCDate(v.getUTCDate()-day+1);return utcDate(v)}function addDays(d:string,n:number){const v=new Date(`${d}T00:00:00.000Z`);v.setUTCDate(v.getUTCDate()+n);return utcDate(v)}function addMonths(d:string,n:number){const v=new Date(`${d}T00:00:00.000Z`);v.setUTCMonth(v.getUTCMonth()+n);return utcDate(v)}
