"use client";
import{useEffect,useState}from"react";import styles from"../documentation.module.css";
type Policy={id:string;title:string;titleEn:string|null;authority:string;region:string;policyType:string;status:string;publishedAt:string|null;effectiveAt:string|null;deadlineAt:string|null;deadlineTimezone:string;summary:string;impact:string;audience:string[];topics:string[];sourceUrl:string;sourceVerifiedAt:string|null;versionCount:number};
type Project={id:string;name:string;nameEn:string|null;leadOrganization:string;region:string;status:string;funding:string;summary:string;opportunityValue:string;topics:string[];url:string};
type Topic={id:string;name:string;nameEn:string|null;category:string;momentum:string;summary:string;evidence:string;policyCount:number;projectCount:number;paperCount:number};
type Payload={counts:{policies:number;projects:number;topics:number;candidates:number};feedHealth:{total:number;healthy:number;failing:number;last_checked_at:string|null};policies:Policy[];projects:Project[];topics:Topic[]};
export default function PoliciesExplorer(){const[q,setQ]=useState(""),[region,setRegion]=useState(""),[type,setType]=useState(""),[status,setStatus]=useState(""),[data,setData]=useState<Payload|null>(null),[error,setError]=useState("");useEffect(()=>{const p=new URLSearchParams();if(q)p.set("q",q);if(region)p.set("region",region);if(type)p.set("type",type);if(status)p.set("status",status);fetch(`/api/policies?${p}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("政策数据暂不可用");return r.json()as Promise<Payload>}).then(x=>{setData(x);setError("")}).catch((e:Error)=>setError(e.message))},[q,region,type,status]);if(error)return<p className={styles.error}>{error}</p>;if(!data)return<p className={styles.loading}>正在载入全球科研政策与项目…</p>;return<>
<section className={styles.statusGrid}><div className={styles.statusCard}><span>已核验政策</span><strong>{data.counts.policies}</strong><p>仅展示官方来源与人工核验条目</p></div><div className={styles.statusCard}><span>研究项目</span><strong>{data.counts.projects}</strong><p>持续追踪的资助计划与研究项目</p></div><div className={styles.statusCard}><span>热点议题</span><strong>{data.counts.topics}</strong><p>政策、项目与论文的共同方向</p></div><div className={styles.statusCard}><span>待审候选</span><strong>{data.counts.candidates}</strong><p>自动发现但尚未公开的政策链接</p></div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>政策与资助</h2><p>自动监控 UKRI、欧盟、国家自然科学基金和香港研资局等官方入口；内容变化保存版本证据，不自动改写已核验摘要。</p></div><div className={styles.filterBar}><label><span>关键词</span><input value={q}onChange={e=>setQ(e.target.value)}placeholder="脑科学、AI、青年人才…"/></label><label><span>地区</span><select value={region}onChange={e=>setRegion(e.target.value)}><option value="">全部</option><option value="UK">英国</option><option value="EU">欧盟</option><option value="CN">中国大陆</option><option value="HK">中国香港</option><option value="GLOBAL">全球</option></select></label><label><span>类型</span><select value={type}onChange={e=>setType(e.target.value)}><option value="">全部</option><option value="funding">资助</option><option value="strategy">战略</option><option value="talent">人才</option><option value="collaboration">合作</option><option value="programme">计划</option></select></label><label><span>状态</span><select value={status}onChange={e=>setStatus(e.target.value)}><option value="">全部</option><option value="open">开放</option><option value="upcoming">即将开放</option><option value="active">执行中</option><option value="watch">持续关注</option><option value="closed">已截止</option></select></label></div><div className={styles.directoryGrid}>{data.policies.map(p=><article className={styles.sourceCard}key={p.id}><div className={styles.sourceCardTop}><span>{regionLabel(p.region)} · {typeLabel(p.policyType)}</span><span className={p.status==="open"?styles.health_healthy:p.status==="closed"?styles.health_failing:styles.health_waiting}>{statusLabel(p.status)}</span></div><h3><a href={p.sourceUrl}target="_blank"rel="noreferrer">{p.title}</a></h3>{p.titleEn&&<p className={styles.institutionEnglish}>{p.titleEn}</p>}<p>{p.summary}</p>{p.impact&&<p className={styles.academicValue}>机会影响：{p.impact}</p>}<div className={styles.chips}>{p.topics.map(x=><span key={x}>{x}</span>)}</div><dl className={styles.sourceMeta}><div><dt>发布机构</dt><dd>{p.authority}</dd></div><div><dt>截止日期</dt><dd>{p.deadlineAt?date(p.deadlineAt):"滚动 / 以官网为准"}</dd></div><div><dt>版本记录</dt><dd>{p.versionCount} 次</dd></div><div><dt>最近核验</dt><dd>{p.sourceVerifiedAt?date(p.sourceVerifiedAt):"等待 Cron"}</dd></div></dl><a className={styles.cardAction}href={p.sourceUrl}target="_blank"rel="noreferrer">查看官方政策 ↗</a></article>)}</div>{!data.policies.length&&<p className={styles.emptyState}>当前筛选没有已核验政策。</p>}</section>
<section className={styles.section}><div className={styles.sectionHead}><h2>研究项目</h2><p>把政策转化为可跟踪的研究计划、资金方向与潜在岗位入口。</p></div><div className={styles.cardGrid}>{data.projects.map(p=><article className={`${styles.card} ${styles.cardDone}`}key={p.id}><span className={styles.cardLabel}>{regionLabel(p.region)} · {p.status}</span><h3><a href={p.url}target="_blank"rel="noreferrer">{p.name}</a></h3><p>{p.summary}</p>{p.funding&&<p className={styles.academicValue}>资金：{p.funding}</p>}<p>{p.opportunityValue}</p></article>)}</div></section>
<section className={styles.section}><div className={styles.sectionHead}><h2>热点议题</h2><p>用于把政策、项目、论文和导师研究方向连接到同一知识图谱。</p></div><div className={styles.cardGrid}>{data.topics.map(t=><article className={styles.card}key={t.id}><span className={styles.cardLabel}>{t.momentum==="rising"?"上升":"持续"} · {t.category}</span><h3>{t.name}{t.nameEn&&<small> / {t.nameEn}</small>}</h3><p>{t.summary}</p><p className={styles.academicValue}>{t.evidence}</p><small>{t.policyCount} 政策 · {t.projectCount} 项目 · {t.paperCount} 论文</small></article>)}</div></section></>}
function date(v:string){return new Date(v).toLocaleDateString("zh-CN",{timeZone:"UTC"})}function regionLabel(v:string){return({UK:"英国",EU:"欧盟",CN:"中国大陆",HK:"中国香港",GLOBAL:"全球"}as Record<string,string>)[v]??v}function typeLabel(v:string){return({funding:"资助",strategy:"战略",talent:"人才",collaboration:"合作",programme:"计划",regulation:"监管"}as Record<string,string>)[v]??v}function statusLabel(v:string){return({open:"开放",active:"执行中",upcoming:"即将开放",closed:"已截止",watch:"持续关注"}as Record<string,string>)[v]??v}
