type ConferenceRow={id:string;series:string;name:string;name_zh:string;field:string;conference_type:string;year:number;city:string;country:string;venue:string;status:string;starts_at:string|null;ends_at:string|null;date_status:string;summary:string;relevance:string;topics_json:string;official_url:string;cfp_url:string|null;proceedings_url:string|null;source_verified_at:string|null;version_count:number};
type DateRow={id:string;conference_id:string;event_type:string;label:string;occurs_at:string|null;ends_at:string|null;timezone:string;date_status:string;action_required:number;official_url:string;notes:string};
type CountRow={total:number};type RunRow={status:string;started_at:string;finished_at:string|null;conferences_checked:number;versions_added:number;failed_count:number};

export async function GET(request:Request){try{
  const url=new URL(request.url),q=(url.searchParams.get("q")??"").trim().slice(0,80),field=url.searchParams.get("field")??"",year=url.searchParams.get("year")??"",status=url.searchParams.get("status")??"";
  const clauses=["c.published=1"],params:(string|number)[]=[];if(q){clauses.push("(c.name LIKE ? OR c.name_zh LIKE ? OR c.series LIKE ? OR c.summary LIKE ? OR c.topics_json LIKE ? OR c.city LIKE ?)");for(let i=0;i<6;i++)params.push(`%${q}%`)}if(field){clauses.push("c.field=?");params.push(field)}if(year){clauses.push("c.year=?");params.push(Number(year))}if(status){clauses.push("c.status=?");params.push(status)}
  const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("D1 binding DB is unavailable");
  const[conferences,dates,allCount,datedCount,run]=await Promise.all([
    env.DB.prepare(`SELECT c.*,COUNT(v.id) version_count FROM academic_conferences c LEFT JOIN conference_versions v ON v.conference_id=c.id WHERE ${clauses.join(" AND ")} GROUP BY c.id ORDER BY CASE c.status WHEN 'open' THEN 0 WHEN 'upcoming' THEN 1 WHEN 'watch' THEN 2 ELSE 3 END,COALESCE(c.starts_at,'9999-12-31'),c.name`).bind(...params).all<ConferenceRow>(),
    env.DB.prepare(`SELECT d.* FROM conference_dates d JOIN academic_conferences c ON c.id=d.conference_id WHERE c.published=1 ORDER BY COALESCE(d.occurs_at,'9999-12-31'),d.label`).all<DateRow>(),
    env.DB.prepare(`SELECT COUNT(*) total FROM academic_conferences WHERE published=1`).first<CountRow>(),
    env.DB.prepare(`SELECT COUNT(*) total FROM conference_dates d JOIN academic_conferences c ON c.id=d.conference_id WHERE c.published=1 AND d.occurs_at IS NOT NULL`).first<CountRow>(),
    env.DB.prepare(`SELECT status,started_at,finished_at,conferences_checked,versions_added,failed_count FROM conference_sync_runs ORDER BY started_at DESC LIMIT 1`).first<RunRow>(),
  ]);
  const byConference=new Map<string,DateRow[]>();for(const item of dates.results){const list=byConference.get(item.conference_id)??[];list.push(item);byConference.set(item.conference_id,list)}
  return Response.json({generatedAt:new Date().toISOString(),counts:{conferences:allCount?.total??0,visible:conferences.results.length,confirmedDates:datedCount?.total??0,fields:4},latestRun:run??null,conferences:conferences.results.map(c=>({id:c.id,series:c.series,name:c.name,nameZh:c.name_zh,field:c.field,conferenceType:c.conference_type,year:c.year,city:c.city,country:c.country,venue:c.venue,status:c.status,startsAt:c.starts_at,endsAt:c.ends_at,dateStatus:c.date_status,summary:c.summary,relevance:c.relevance,topics:parse(c.topics_json),officialUrl:c.official_url,cfpUrl:c.cfp_url,proceedingsUrl:c.proceedings_url,sourceVerifiedAt:c.source_verified_at,versionCount:c.version_count,dates:(byConference.get(c.id)??[]).map(d=>({id:d.id,eventType:d.event_type,label:d.label,occursAt:d.occurs_at,endsAt:d.ends_at,timezone:d.timezone,dateStatus:d.date_status,actionRequired:Boolean(d.action_required),officialUrl:d.official_url,notes:d.notes}))}))},{headers:{"Cache-Control":"no-store"}});
}catch(error){console.error(JSON.stringify({event:"radar.conferences_api.failed",error:message(error)}));return Response.json({error:"conference radar is temporarily unavailable"},{status:503})}}
function parse(value:string){try{return JSON.parse(value)as string[]}catch{return[]}}
function message(error:unknown){return error instanceof Error?error.message.slice(0,500):String(error).slice(0,500)}
