"use client";
import { useEffect, useMemo, useState } from "react";
import styles from "../documentation.module.css";

type Institution={id:string;name:string;nameEn:string|null;institutionType:string;topics:string[];mark:string;summary:string;note:string;url:string;opportunityUrl:string|null;priority:string};
type Opportunity={id:string;name:string;org:string;kind:string;status:string;deadline:string;mastersEligible:boolean;phdBridgeDetails:string|null;why:string;action:string;tags:string[];url:string};
type Source={id:string;name:string;url:string;lastSuccessAt:string|null;consecutiveFailures:number};
type Payload={institutions:Institution[];opportunities:Opportunity[];sources:Source[]};

export default function BeijingExplorer(){
  const[data,setData]=useState<Payload|null>(null);const[error,setError]=useState("");const[type,setType]=useState("");const[kind,setKind]=useState("");
  useEffect(()=>{fetch("/api/beijing",{cache:"no-store"}).then(async(response)=>{if(!response.ok)throw new Error("北京机构数据暂不可用");return response.json() as Promise<Payload>}).then(setData).catch((reason:Error)=>setError(reason.message))},[]);
  const institutions=useMemo(()=>data?.institutions.filter((item)=>!type||item.institutionType===type)??[],[data,type]);
  const opportunities=useMemo(()=>data?.opportunities.filter((item)=>!kind||item.kind===kind)??[],[data,kind]);
  if(error)return <p className={`${styles.state} ${styles.stateError}`}>{error}</p>;
  if(!data)return <p className={styles.loading}>正在读取北京高校、实验室和中科院机会…</p>;
  return <>
    <section className={styles.section}><div className={styles.sectionHead}><h2>机构与实验室</h2><p>首批聚焦脑科学、认知科学、脑机接口和类脑智能。名称、定位和机会入口来自机构官方页面，并持续扩展。</p></div><div className={styles.filterBar}><label><span>机构类型</span><select value={type} onChange={(event)=>setType(event.target.value)}><option value="">全部</option><option value="university">高校/高校实验室</option><option value="national_lab">全国/国家重点实验室</option><option value="cas_institute">中科院研究所</option><option value="research_institute">科研机构</option></select></label></div><p className={styles.note}>当前显示 {institutions.length} / {data.institutions.length} 个北京相关机构；全国/国家级重点实验室 {data.institutions.filter((item)=>item.institutionType==="national_lab").length} 个，中科院研究所 {data.institutions.filter((item)=>item.institutionType==="cas_institute").length} 个。</p><div className={styles.directoryGrid}>{institutions.map((item)=><article className={styles.sourceCard} key={item.id}><div className={styles.sourceCardTop}><span>{typeLabel(item.institutionType)}</span><span className={item.priority==="critical"?styles.good:styles.pending}>{item.mark}</span></div><h3><a href={item.url} target="_blank" rel="noreferrer">{item.name}</a></h3>{item.nameEn&&<p className={styles.institutionEnglish} lang="en">{item.nameEn}</p>}<div className={styles.chips}>{item.topics.map((topic)=><span key={topic}>{topic}</span>)}</div><p>{item.summary}</p><p className={styles.academicValue}>{item.note}</p>{item.opportunityUrl&&<a className={styles.cardAction} href={item.opportunityUrl} target="_blank" rel="noreferrer">查看官方机会 ↗</a>}</article>)}</div></section>
    <section className={styles.section}><div className={styles.sectionHead}><h2>当前机会</h2><p>包括硕士可申请的科研助理与实习、2027 博士通道，以及需要博士学位的研究岗位；不同职级明确区分。</p></div><div className={styles.filterBar}><label><span>机会类型</span><select value={kind} onChange={(event)=>setKind(event.target.value)}><option value="">全部</option><option value="博士">博士</option><option value="科研助理">科研助理</option><option value="实习">实习</option><option value="研究岗位">研究岗位</option></select></label></div><div className={styles.paperList}>{opportunities.map((item)=><article className={styles.paperCard} key={item.id}><div className={styles.sourceCardTop}><span>{item.org} · {item.kind}</span><span className={item.status==="立即行动"?styles.good:styles.pending}>{item.status}</span></div><h3><a href={item.url} target="_blank" rel="noreferrer">{item.name}</a></h3><p>{item.deadline}</p><div className={styles.chips}>{item.mastersEligible&&<span>硕士可申请</span>}{item.tags.map((tag)=><span key={tag}>{tag}</span>)}</div><p>{item.why}</p>{item.phdBridgeDetails&&<p className={styles.academicValue}>{item.phdBridgeDetails}</p>}<p className={styles.paperTakeaway}><b>下一步：</b>{item.action}</p></article>)}</div></section>
    <section className={styles.section}><div className={styles.sectionHead}><h2>官方信息源</h2><p>{data.sources.length} 个直接关联上述机构与机会的官方入口；每 6 小时 Cron 触发后按优先级和到期时间检查。</p></div><div className={styles.compactSourceList}>{data.sources.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer"><span className={source.consecutiveFailures?styles.pending:styles.good}>●</span><b>{source.name}</b><small>{source.lastSuccessAt?`最近成功 ${new Date(source.lastSuccessAt).toLocaleDateString("zh-CN")}`:"等待首次检查"}</small></a>)}</div></section>
  </>;
}
function typeLabel(value:string){return({university:"高校/高校实验室",national_lab:"全国/国家重点实验室",cas_institute:"中科院研究所",research_institute:"科研机构"}as Record<string,string>)[value]??value}
