type InstitutionRow={id:string;source_id:string|null;name:string;name_en:string|null;institution_type:string;city:string;topics_json:string;mark:string;summary:string;note:string;url:string;opportunity_url:string|null;priority:string;source_verified_at:string|null};
type OpportunityRow={id:string;source_id:string|null;name:string;org:string;kind:string;status:string;fit:string;location:string;deadline:string;deadline_at:string|null;deadline_status:string;masters_eligible:number;eligibility_details:string;phd_bridge_details:string|null;why:string;action:string;tags_json:string;url:string;source_verified_at:string|null};
type SourceRow={id:string;name:string;url:string;regions_json:string;priority:string;enabled:number;last_success_at:string|null;consecutive_failures:number};
const configs={
shanghai:{name:"上海",nameEn:"Shanghai",cities:["上海"],locationTerms:["上海"],sourceTerms:["上海","复旦"],regionCode:null,focus:"复旦、上海交大、上海人工智能实验室及脑智交叉研究机会"},
shenzhen:{name:"深圳",nameEn:"Shenzhen",cities:["深圳"],locationTerms:["深圳"],sourceTerms:["深圳","鹏城"],regionCode:null,focus:"深圳先进院、清华深圳、鹏城国家实验室与湾区脑科学机会"},
uk:{name:"英国",nameEn:"United Kingdom",cities:["Oxford","Cambridge","London","Edinburgh"],locationTerms:["Oxford","Cambridge","London","Edinburgh","英国"],sourceTerms:[],regionCode:"UK",focus:"牛津、剑桥、UCL、KCL、帝国理工、爱丁堡及相关研究机构"},
ireland:{name:"爱尔兰",nameEn:"Ireland",cities:["Dublin"],locationTerms:["Ireland","Dublin","爱尔兰"],sourceTerms:[],regionCode:"IE",focus:"Trinity College Dublin、UCD 以及英国/爱尔兰联合校招入口"},
"hong-kong":{name:"中国香港",nameEn:"Hong Kong, China",cities:["香港"],locationTerms:["香港","Hong Kong"],sourceTerms:[],regionCode:"HK",focus:"港大、港中文、港科大、港城大及 HKPFS、科研助理和实习机会"},
}as const;
export async function GET(request:Request){try{const slug=new URL(request.url).searchParams.get("slug")??"";if(!(slug in configs))return Response.json({error:"unknown region"},{status:404});const config=configs[slug as keyof typeof configs];const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("D1 binding DB is unavailable");const[institutions,opportunities,sources]=await Promise.all([env.DB.prepare(`SELECT id,source_id,name,name_en,institution_type,city,topics_json,mark,summary,note,url,opportunity_url,priority,source_verified_at FROM institutions WHERE published=1 ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,sort_order`).all<InstitutionRow>(),env.DB.prepare(`SELECT id,source_id,name,org,kind,status,fit,location,deadline,deadline_at,deadline_status,masters_eligible,eligibility_details,phd_bridge_details,why,action,tags_json,url,source_verified_at FROM opportunities WHERE published=1 ORDER BY COALESCE(deadline_at,'9999-12-31'),created_at DESC`).all<OpportunityRow>(),env.DB.prepare(`SELECT id,name,url,regions_json,priority,enabled,last_success_at,consecutive_failures FROM sources ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,name`).all<SourceRow>()]);const selectedInstitutions=institutions.results.filter((row)=>config.cities.includes(row.city as never));const selectedOpportunities=opportunities.results.filter((row)=>config.locationTerms.some((term)=>row.location.includes(term)));const linked=new Set([...selectedInstitutions.map((row)=>row.source_id),...selectedOpportunities.map((row)=>row.source_id)].filter(Boolean));const selectedSources=sources.results.filter((row)=>linked.has(row.id)||config.sourceTerms.some((term)=>row.name.includes(term))||(config.regionCode&&array(row.regions_json).includes(config.regionCode)));return Response.json({generatedAt:new Date().toISOString(),region:{slug,...config},counts:{institutions:selectedInstitutions.length,opportunities:selectedOpportunities.length,sources:selectedSources.length},institutions:selectedInstitutions.map((row)=>({...row,nameEn:row.name_en,institutionType:row.institution_type,topics:array(row.topics_json),opportunityUrl:row.opportunity_url,sourceVerifiedAt:row.source_verified_at})),opportunities:selectedOpportunities.map((row)=>({...row,deadlineAt:row.deadline_at,deadlineStatus:row.deadline_status,mastersEligible:Boolean(row.masters_eligible),eligibilityDetails:row.eligibility_details,phdBridgeDetails:row.phd_bridge_details,tags:array(row.tags_json),sourceVerifiedAt:row.source_verified_at})),sources:selectedSources.map((row)=>({...row,enabled:Boolean(row.enabled),lastSuccessAt:row.last_success_at,consecutiveFailures:row.consecutive_failures}))},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error(JSON.stringify({event:"radar.region_api.failed",error:message(error)}));return Response.json({error:"regional intelligence is temporarily unavailable"},{status:503})}}
function array(value:string):string[]{try{const parsed:unknown=JSON.parse(value);return Array.isArray(parsed)?parsed.filter((item):item is string=>typeof item==="string"):[]}catch{return[]}}
function message(error:unknown){return error instanceof Error?error.message.slice(0,500):String(error).slice(0,500)}
