"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "../documentation.module.css";

type Feed={id:string;name:string;url:string;region:string;candidate_type:string;last_checked_at:string|null;last_success_at:string|null;last_status_code:number|null;consecutive_failures:number;last_error:string|null};
type Org={id:string;name:string;candidate_url:string;candidate_type:string;region:string;status:string;confidence:number;first_seen_at:string;last_seen_at:string;feed_name:string;feed_url:string};
type Opp={id:string;title:string;org:string;kind:string|null;location:string|null;deadline:string|null;opportunity_status:string|null;canonical_url:string;state:string;first_seen_at:string;last_seen_at:string;source_name:string;evidence_count:number};
type Payload={generatedAt:string;counts:{feeds:number;organizationCandidates:number;opportunityCandidates:number;listingSources:number};feeds:Feed[];organizations:Org[];opportunities:Opp[];latestRun:{status:string;started_at:string;finished_at:string|null;feeds_checked:number;candidates_found:number;failed_count:number}|null};

export default function DiscoveryExplorer(){
  const[data,setData]=useState<Payload|null>(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[region,setRegion]=useState("");
  useEffect(()=>{fetch("/api/discovery",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("持续发现数据暂不可用");return r.json() as Promise<Payload>}).then(setData).catch((e:Error)=>setError(e.message))},[]);
  const orgs=useMemo(()=>data?.organizations.filter(x=>(!region||x.region===region)&&(!query||`${x.name} ${x.feed_name} ${x.region}`.toLowerCase().includes(query.toLowerCase())))??[],[data,query,region]);
  const opps=useMemo(()=>data?.opportunities.filter(x=>!query||`${x.title} ${x.org} ${x.source_name} ${x.kind??""}`.toLowerCase().includes(query.toLowerCase()))??[],[data,query]);
  if(error)return <p className={`${styles.state} ${styles.stateError}`}>{error}</p>;
  if(!data)return <p className={styles.loading}>正在读取新公司、新研究机构和新机会候选…</p>;
  return <>
    <section className={styles.statusGrid}><Metric name="招聘发现源" value={data.counts.listingSources} note="同站新岗位自动抽取"/><Metric name="可信机构目录" value={data.counts.feeds} note="官方目录定时检查"/><Metric name="新机会候选" value={data.counts.opportunityCandidates} note="核验后才公开"/><Metric name="新机构候选" value={data.counts.organizationCandidates} note="不会自动发布"/></section>
    <section className={styles.section}><div className={styles.sectionHead}><h2>发现边界</h2><p>系统自动发现、去重和保存证据；新公司、新研究机构与高风险岗位信息先作为候选，不会直接进入公开机会库。截止日期、毕业批次、签证与学历要求必须经过核验。</p></div><div className={styles.flow}><Step n="01" title="官方入口" text="Cron 检查已登记招聘页与可信机构目录"/><Step n="02" title="抽取" text="识别同站新岗位和目录中的外部机构链接"/><Step n="03" title="去重" text="规范 URL，对比已知来源、机构和历史候选"/><Step n="04" title="留证" text="记录首次/最近发现时间、来源和置信度"/><Step n="05" title="核验发布" text="候选核验后才加入来源或公开机会"/></div>{data.latestRun&&<p className={styles.note}>最近机构发现运行：{data.latestRun.status} · 检查 {data.latestRun.feeds_checked} 个目录 · 发现 {data.latestRun.candidates_found} 个链接候选 · 失败 {data.latestRun.failed_count} 个。</p>}</section>
    <section className={styles.section}><div className={styles.sectionHead}><h2>新机构候选</h2><p>来自 UKRI、中科院等官方目录；“候选”只代表在可信目录中发现，不代表已确认与目标方向相关或正在招聘。</p></div><div className={styles.filterBar}><label><span>搜索</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="公司、研究机构、机会或来源"/></label><label><span>地区</span><select value={region} onChange={e=>setRegion(e.target.value)}><option value="">全部</option><option value="中国">中国</option><option value="英国">英国</option></select></label></div><div className={styles.directoryGrid}>{orgs.map(x=><article className={styles.sourceCard} key={x.id}><div className={styles.sourceCardTop}><span>{x.region} · {x.candidate_type}</span><span className={styles.pending}>候选 {x.confidence}%</span></div><h3><a href={x.candidate_url} target="_blank" rel="noreferrer">{x.name}</a></h3><p>发现自 <a href={x.feed_url} target="_blank" rel="noreferrer">{x.feed_name}</a></p><dl className={styles.sourceMeta}><div><dt>首次发现</dt><dd>{date(x.first_seen_at)}</dd></div><div><dt>最近发现</dt><dd>{date(x.last_seen_at)}</dd></div></dl></article>)}</div>{!orgs.length&&<p className={styles.note}>等待首次 Cron 检查；目录已配置，候选会在运行后出现。</p>}</section>
    <section className={styles.section}><div className={styles.sectionHead}><h2>新机会候选</h2><p>已登记的公司、大学与研究机构招聘页会持续抽取同站新岗位。候选可检索，但不会替代已核验的公开机会。</p></div><div className={styles.paperList}>{opps.map(x=><article className={styles.paperCard} key={x.id}><div className={styles.sourceCardTop}><span>{x.source_name} · {x.kind??"类型待判定"}</span><span className={styles.pending}>{x.state==="review"?"待核验":"已观察"}</span></div><h3><a href={x.canonical_url} target="_blank" rel="noreferrer">{x.title}</a></h3><p>{x.org}{x.location?` · ${x.location}`:""}{x.deadline?` · ${x.deadline}`:""}</p><div className={styles.chips}><span>证据 {x.evidence_count}</span><span>首次 {date(x.first_seen_at)}</span><span>最近 {date(x.last_seen_at)}</span></div></article>)}</div>{!opps.length&&<p className={styles.note}>当前还没有待核验候选；下一次招聘源 Cron 会继续发现。</p>}</section>
    <section className={styles.section}><div className={styles.sectionHead}><h2>可信发现目录</h2><p>目录负责发现“谁值得新增跟踪”，招聘源负责发现“出现了哪些新岗位”。两类来源分开管理。</p></div><div className={styles.compactSourceList}>{data.feeds.map(x=><a key={x.id} href={x.url} target="_blank" rel="noreferrer"><span className={x.consecutive_failures?styles.pending:x.last_success_at?styles.good:styles.pending}>●</span><b>{x.name}</b><small>{x.last_success_at?`成功 ${date(x.last_success_at)} · HTTP ${x.last_status_code}`:x.last_error??"等待首次检查"}</small></a>)}</div></section>
  </>;
}
function Metric({name,value,note}:{name:string;value:number;note:string}){return <div className={styles.metric}><span>{name}</span><strong>{value}</strong><small>{note}</small></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <div className={styles.flowStep}><b>{n}</b><h3>{title}</h3><p>{text}</p></div>}
function date(value:string){return new Date(value).toLocaleString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"})}
