type PolicyRow={id:string;title:string;title_en:string|null;authority:string;region:string;policy_type:string;status:string;published_at:string|null;effective_at:string|null;deadline_at:string|null;deadline_timezone:string;summary:string;impact:string;audience_json:string;topics_json:string;source_url:string;source_verified_at:string|null;version_count:number};
type ProjectRow={id:string;name:string;name_en:string|null;lead_organization:string;region:string;status:string;start_at:string|null;end_at:string|null;funding:string;summary:string;opportunity_value:string;topics_json:string;url:string;source_verified_at:string|null};
type TopicRow={id:string;name:string;name_en:string|null;category:string;momentum:string;summary:string;evidence:string;policy_count:number;project_count:number;paper_count:number;updated_at:string};
export async function GET(request:Request){
  try{
    const url=new URL(request.url),q=(url.searchParams.get("q")??"").trim().slice(0,80),region=allowed(url.searchParams.get("region"),["UK","EU","CN","HK","GLOBAL"]),policyType=allowed(url.searchParams.get("type"),["strategy","funding","talent","regulation","collaboration","programme"]),status=allowed(url.searchParams.get("status"),["open","active","upcoming","closed","watch"]);
    const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("D1 binding DB is unavailable");
    const where=["p.published=1","p.review_status='verified'"],params:unknown[]=[];if(q){where.push("(p.title LIKE ? OR p.title_en LIKE ? OR p.authority LIKE ? OR p.summary LIKE ? OR p.topics_json LIKE ?)");for(let i=0;i<5;i++)params.push(`%${q}%`)}if(region){where.push("p.region=?");params.push(region)}if(policyType){where.push("p.policy_type=?");params.push(policyType)}if(status){where.push("p.status=?");params.push(status)}
    const[policies,projects,topics,health,runs,candidates]=await Promise.all([
      env.DB.prepare(`SELECT p.id,p.title,p.title_en,p.authority,p.region,p.policy_type,p.status,p.published_at,p.effective_at,p.deadline_at,p.deadline_timezone,p.summary,p.impact,p.audience_json,p.topics_json,p.source_url,p.source_verified_at,(SELECT COUNT(*) FROM policy_versions v WHERE v.policy_id=p.id) version_count FROM research_policies p WHERE ${where.join(" AND ")} ORDER BY CASE p.status WHEN 'open' THEN 0 WHEN 'upcoming' THEN 1 WHEN 'active' THEN 2 ELSE 3 END,COALESCE(p.deadline_at,'9999-12-31'),p.updated_at DESC`).bind(...params).all<PolicyRow>(),
      env.DB.prepare(`SELECT id,name,name_en,lead_organization,region,status,start_at,end_at,funding,summary,opportunity_value,topics_json,url,source_verified_at FROM research_projects WHERE published=1 ORDER BY CASE status WHEN 'active' THEN 0 WHEN 'upcoming' THEN 1 ELSE 2 END,updated_at DESC`).all<ProjectRow>(),
      env.DB.prepare(`SELECT id,name,name_en,category,momentum,summary,evidence,policy_count,project_count,paper_count,updated_at FROM research_topics ORDER BY CASE momentum WHEN 'rising' THEN 0 WHEN 'stable' THEN 1 ELSE 2 END,policy_count+project_count DESC`).all<TopicRow>(),
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN last_success_at IS NOT NULL AND consecutive_failures=0 THEN 1 ELSE 0 END) healthy,SUM(CASE WHEN consecutive_failures>0 THEN 1 ELSE 0 END) failing,MAX(last_checked_at) last_checked_at FROM policy_feeds WHERE enabled=1`).first<{total:number;healthy:number;failing:number;last_checked_at:string|null}>(),
      env.DB.prepare(`SELECT id,trigger,status,started_at,finished_at,feeds_checked,policies_checked,candidates_found,versions_added,failed_count FROM policy_sync_runs ORDER BY started_at DESC LIMIT 12`).all(),
      env.DB.prepare(`SELECT COUNT(*) total FROM policy_candidates WHERE status='candidate'`).first<{total:number}>(),
    ]);
    return Response.json({generatedAt:new Date().toISOString(),counts:{policies:policies.results.length,projects:projects.results.length,topics:topics.results.length,candidates:candidates?.total??0},feedHealth:health??{total:0,healthy:0,failing:0,last_checked_at:null},policies:policies.results.map(p=>({...p,titleEn:p.title_en,policyType:p.policy_type,publishedAt:p.published_at,effectiveAt:p.effective_at,deadlineAt:p.deadline_at,deadlineTimezone:p.deadline_timezone,audience:json(p.audience_json),topics:json(p.topics_json),sourceUrl:p.source_url,sourceVerifiedAt:p.source_verified_at,versionCount:p.version_count})),projects:projects.results.map(p=>({...p,nameEn:p.name_en,leadOrganization:p.lead_organization,startAt:p.start_at,endAt:p.end_at,opportunityValue:p.opportunity_value,topics:json(p.topics_json),sourceVerifiedAt:p.source_verified_at})),topics:topics.results.map(t=>({...t,nameEn:t.name_en,policyCount:t.policy_count,projectCount:t.project_count,paperCount:t.paper_count,updatedAt:t.updated_at})),runs:runs.results},{headers:{"Cache-Control":"public, max-age=300"}});
  }catch(error){console.error(JSON.stringify({event:"radar.policies_api.failed",error:message(error)}));return Response.json({error:"research policy radar is temporarily unavailable"},{status:503})}
}
function allowed(value:string|null,values:string[]){return value&&values.includes(value)?value:""}
function json(value:string){try{const parsed:unknown=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}}
function message(error:unknown){return error instanceof Error?error.message.slice(0,500):String(error).slice(0,500)}
