type Row={id:string;name:string;org:string;kind:string;status:string;location:string;deadline:string;deadline_at:string|null;opens_at:string|null;deadline_timezone:string;deadline_status:string;action:string;url:string;masters_eligible:number};
type CalendarItem={id:string;opportunityId:string;date:string;time:string|null;eventType:"deadline"|"opening"|"task"|"conference";title:string;org:string;kind:string;status:string;dateStatus:string;timezone:string;url:string;action:string};
type PolicyDeadline={id:string;title:string;authority:string;policy_type:string;status:string;deadline_at:string;deadline_timezone:string;source_url:string;impact:string};
type ConferenceRow={id:string;name:string;name_zh:string;starts_at:string;ends_at:string|null;city:string;country:string;official_url:string};
type ConferenceDate={id:string;conference_id:string;name:string;name_zh:string;event_type:string;label:string;occurs_at:string;ends_at:string|null;timezone:string;official_url:string;action_required:number};
export async function GET(){try{
  const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("D1 binding DB is unavailable");
  const[result,policyResult,conferenceResult,conferenceDates]=await Promise.all([
    env.DB.prepare(`SELECT id,name,org,kind,status,location,deadline,deadline_at,opens_at,deadline_timezone,deadline_status,action,url,masters_eligible FROM opportunities WHERE published=1 ORDER BY COALESCE(deadline_at,'9999-12-31'),created_at DESC`).all<Row>(),
    env.DB.prepare(`SELECT id,title,authority,policy_type,status,deadline_at,deadline_timezone,source_url,impact FROM research_policies WHERE published=1 AND review_status='verified' AND deadline_at IS NOT NULL ORDER BY deadline_at`).all<PolicyDeadline>(),
    env.DB.prepare(`SELECT id,name,name_zh,starts_at,ends_at,city,country,official_url FROM academic_conferences WHERE published=1 AND starts_at IS NOT NULL ORDER BY starts_at`).all<ConferenceRow>(),
    env.DB.prepare(`SELECT d.id,d.conference_id,c.name,c.name_zh,d.event_type,d.label,d.occurs_at,d.ends_at,d.timezone,d.official_url,d.action_required FROM conference_dates d JOIN academic_conferences c ON c.id=d.conference_id WHERE c.published=1 AND d.occurs_at IS NOT NULL ORDER BY d.occurs_at`).all<ConferenceDate>(),
  ]);
  const items:CalendarItem[]=[];
  for(const row of result.results){if(row.opens_at)items.push(event(row,"opening",row.opens_at,`开放：${row.name}`));if(row.deadline_at){items.push(event(row,"deadline",row.deadline_at,`截止：${row.name}`));for(const task of taskSchedule(row))if(task.date>=today())items.push(task)}}
  for(const p of policyResult.results)items.push({id:`policy:${p.id}:deadline`,opportunityId:`policy:${p.id}`,date:p.deadline_at.slice(0,10),time:p.deadline_at.includes("T")?p.deadline_at.slice(11,16):null,eventType:"deadline",title:`政策截止：${p.title}`,org:p.authority,kind:"科研政策",status:p.status,dateStatus:"confirmed",timezone:p.deadline_timezone,url:p.source_url,action:p.impact||"核对官方申请条件并建立材料清单"});
  for(const c of conferenceResult.results)items.push({id:`conference:${c.id}:event`,opportunityId:`conference:${c.id}`,date:c.starts_at.slice(0,10),time:null,eventType:"conference",title:`会议召开：${c.name_zh}`,org:c.name,kind:"学术会议",status:"upcoming",dateStatus:"confirmed",timezone:"local",url:c.official_url,action:`${[c.city,c.country].filter(Boolean).join(" · ")} · ${c.starts_at}${c.ends_at?`—${c.ends_at}`:""}`});
  for(const d of conferenceDates.results)items.push({id:`conference-date:${d.id}`,opportunityId:`conference:${d.conference_id}`,date:d.occurs_at.slice(0,10),time:d.occurs_at.includes("T")?d.occurs_at.slice(11,16):null,eventType:d.action_required?"deadline":"conference",title:`${d.label}：${d.name}`,org:d.name_zh,kind:"学术会议",status:d.action_required?"立即行动":"持续关注",dateStatus:"confirmed",timezone:d.timezone,url:d.official_url,action:d.action_required?"按官方要求准备并在截止前提交；注意时区。":"记录结果或阶段变化并回到官网核验。"});
  const conferenceDeadlineList=conferenceDates.results.filter(d=>d.action_required).map(d=>({id:`conference-date:${d.id}`,name:`${d.label}：${d.name}`,org:d.name_zh,kind:"学术会议",status:"立即行动",location:"",deadline:`官方会议节点 · ${d.timezone}`,deadlineAt:d.occurs_at,opensAt:null,deadlineTimezone:d.timezone,deadlineStatus:"confirmed",action:"按官方要求准备并在截止前提交",url:d.official_url,mastersEligible:false}));
  const dated=[...result.results.filter(row=>row.deadline_at).map(formatOpportunity),...policyResult.results.map(p=>({id:`policy:${p.id}`,name:p.title,org:p.authority,kind:"科研政策",status:p.status,location:"",deadline:`官方政策截止 · ${p.deadline_timezone}`,deadlineAt:p.deadline_at,opensAt:null,deadlineTimezone:p.deadline_timezone,deadlineStatus:"confirmed",action:p.impact,url:p.source_url,mastersEligible:false})),...conferenceDeadlineList].sort((a,b)=>(a.deadlineAt??"").localeCompare(b.deadlineAt??""));
  const rolling=result.results.filter(row=>row.deadline_status==="rolling").map(formatOpportunity),pending=result.results.filter(row=>!row.deadline_at&&row.deadline_status!=="rolling").map(formatOpportunity);
  return Response.json({generatedAt:new Date().toISOString(),today:today(),items:items.sort((a,b)=>a.date.localeCompare(b.date)||eventOrder(a.eventType)-eventOrder(b.eventType)),deadlines:dated,rolling,pending,counts:{all:result.results.length+policyResult.results.length+conferenceResult.results.length,dated:dated.length,rolling:rolling.length,pending:pending.length,policyDeadlines:policyResult.results.length,conferenceEvents:conferenceResult.results.length,conferenceDeadlines:conferenceDeadlineList.length}},{headers:{"Cache-Control":"no-store"}});
}catch(error){console.error(JSON.stringify({event:"radar.calendar_api.failed",error:message(error)}));return Response.json({error:"calendar is temporarily unavailable"},{status:503})}}
function event(row:Row,eventType:"deadline"|"opening",value:string,title:string):CalendarItem{return{id:`${row.id}:${eventType}`,opportunityId:row.id,date:value.slice(0,10),time:value.includes("T")?value.slice(11,16):null,eventType,title,org:row.org,kind:row.kind,status:row.status,dateStatus:row.deadline_status,timezone:row.deadline_timezone,url:row.url,action:row.action}}
function taskSchedule(row:Row):CalendarItem[]{if(!row.deadline_at)return[];const deadline=new Date(`${row.deadline_at.slice(0,10)}T12:00:00Z`);const definitions:Array<[number,string,string]>=[[30,"确定申请并建立材料清单","确认资格、推荐人和缺口"],[14,"完成申请初稿","完成研究计划、个人陈述和简历初稿"],[7,"完成材料复核","催收推荐信并逐项核对官方要求"],[3,"提前提交","不要等待最后一天，完成系统提交和回执保存"],[0,"截止日复核","确认提交状态、付款和推荐信状态"]];return definitions.map(([offset,title,detail])=>{const date=new Date(deadline);date.setUTCDate(date.getUTCDate()-offset);return{id:`${row.id}:task:${offset}`,opportunityId:row.id,date:date.toISOString().slice(0,10),time:null,eventType:"task",title:`${title}：${row.name}`,org:row.org,kind:row.kind,status:row.status,dateStatus:row.deadline_status,timezone:row.deadline_timezone,url:row.url,action:detail}})}
function formatOpportunity(row:Row){return{id:row.id,name:row.name,org:row.org,kind:row.kind,status:row.status,location:row.location,deadline:row.deadline,deadlineAt:row.deadline_at,opensAt:row.opens_at,deadlineTimezone:row.deadline_timezone,deadlineStatus:row.deadline_status,action:row.action,url:row.url,mastersEligible:Boolean(row.masters_eligible)}}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function eventOrder(type:CalendarItem["eventType"]){return type==="deadline"?0:type==="opening"?1:type==="conference"?2:3}
function message(error:unknown){return error instanceof Error?error.message.slice(0,500):String(error).slice(0,500)}
