type Row={id:string;name:string;org:string;kind:string;status:string;fit:string;location:string;deadline:string;deadline_at:string|null;deadline_status:string;funding_type:string;funding_details:string;masters_eligible:number;eligibility_details:string;phd_bridge_details:string|null;why:string;action:string;tags_json:string;url:string;source_verified_at:string|null;created_at:string;source_name:string|null;source_last_success_at:string|null};
type CountRow={total:number};
const kinds=["博士","联培博士","科研助理","校招","实习","研究岗位"] as const,statuses=["立即行动","等待开放","持续关注"] as const,deadlineStatuses=["confirmed","estimated","rolling","unknown","closed"] as const,fundingTypes=["full","partial","mixed","self_funded","unknown"] as const;
const regions:{[key:string]:string[]}={中国:["北京","上海","深圳","杭州","广州","南京","天津","武汉","成都","苏州","哈尔滨","全国"],英国:["London","Cambridge","Manchester","Sheffield","Bristol","Reading","Oxford","Edinburgh","UK","英国"],爱尔兰:["Dublin","Ireland","爱尔兰"],中国香港:["香港","Hong Kong"]};

export async function GET(request:Request){
  try{
    const url=new URL(request.url),q=clean(url.searchParams.get("q"),80),kind=allowed(url.searchParams.get("kind"),kinds),status=allowed(url.searchParams.get("status"),statuses),deadlineStatus=allowed(url.searchParams.get("deadlineStatus"),deadlineStatuses),fundingType=allowed(url.searchParams.get("fundingType"),fundingTypes),region=regions[url.searchParams.get("region")??""]?url.searchParams.get("region"):null,masters=url.searchParams.get("masters")==="1",page=Math.max(1,Math.min(1000,Number(url.searchParams.get("page"))||1)),pageSize=24,sort=allowed(url.searchParams.get("sort"),["priority","deadline","newest","organization"] as const)??"priority";
    const clauses=["o.published=1"],bindings:(string|number)[]=[];
    if(q){const p=`%${q}%`;clauses.push("(o.name LIKE ? OR o.org LIKE ? OR o.location LIKE ? OR o.why LIKE ? OR o.action LIKE ? OR o.tags_json LIKE ?)");bindings.push(p,p,p,p,p,p)}
    if(kind){clauses.push("o.kind=?");bindings.push(kind)}if(status){clauses.push("o.status=?");bindings.push(status)}if(deadlineStatus){clauses.push("o.deadline_status=?");bindings.push(deadlineStatus)}if(fundingType){clauses.push("o.funding_type=?");bindings.push(fundingType)}if(masters)clauses.push("o.masters_eligible=1");
    if(region){const terms=regions[region]??[];clauses.push(`(${terms.map(()=>"o.location LIKE ?").join(" OR ")})`);bindings.push(...terms.map(x=>`%${x}%`))}
    const order={priority:"CASE o.status WHEN '立即行动' THEN 0 WHEN '等待开放' THEN 1 ELSE 2 END,CASE o.deadline_status WHEN 'confirmed' THEN 0 WHEN 'rolling' THEN 1 WHEN 'estimated' THEN 2 ELSE 3 END,COALESCE(o.deadline_at,'9999-12-31'),o.created_at DESC",deadline:"CASE WHEN o.deadline_at IS NULL THEN 1 ELSE 0 END,o.deadline_at,o.created_at DESC",newest:"o.created_at DESC",organization:"o.org,o.name"}[sort];
    const{env}=await import("cloudflare:workers");if(!env.DB)throw new Error("D1 binding DB is unavailable");const where=clauses.join(" AND "),offset=(page-1)*pageSize;
    const[list,count,facets]=await Promise.all([
      env.DB.prepare(`SELECT o.id,o.name,o.org,o.kind,o.status,o.fit,o.location,o.deadline,o.deadline_at,o.deadline_status,o.funding_type,o.funding_details,o.masters_eligible,o.eligibility_details,o.phd_bridge_details,o.why,o.action,o.tags_json,o.url,o.source_verified_at,o.created_at,s.name source_name,s.last_success_at source_last_success_at FROM opportunities o LEFT JOIN sources s ON s.id=o.source_id WHERE ${where} ORDER BY ${order} LIMIT ? OFFSET ?`).bind(...bindings,pageSize,offset).all<Row>(),
      env.DB.prepare(`SELECT COUNT(*) total FROM opportunities o WHERE ${where}`).bind(...bindings).first<CountRow>(),
      env.DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='立即行动' THEN 1 ELSE 0 END) immediate,SUM(CASE WHEN masters_eligible=1 THEN 1 ELSE 0 END) masters,SUM(CASE WHEN deadline_at IS NOT NULL THEN 1 ELSE 0 END) dated FROM opportunities WHERE published=1`).first(),
    ]);
    return Response.json({generatedAt:new Date().toISOString(),page,pageSize,total:Number(count?.total??0),facets,opportunities:list.results.map(format)},{headers:{"Cache-Control":"no-store"}})
  }catch(error){console.error(JSON.stringify({event:"radar.opportunity_list.failed",error:message(error)}));return Response.json({error:"全部机会暂不可用"},{status:503})}
}
function format(row:Row){return{id:row.id,name:row.name,org:row.org,kind:row.kind,status:row.status,fit:row.fit,location:row.location,deadline:row.deadline,deadlineAt:row.deadline_at,deadlineStatus:row.deadline_status,fundingType:row.funding_type,fundingDetails:row.funding_details,mastersEligible:Boolean(row.masters_eligible),eligibilityDetails:row.eligibility_details,phdBridgeDetails:row.phd_bridge_details,why:row.why,action:row.action,tags:array(row.tags_json),url:row.url,sourceVerifiedAt:row.source_verified_at,createdAt:row.created_at,source:{name:row.source_name,lastSuccessAt:row.source_last_success_at}}}
function array(value:string){try{const x:unknown=JSON.parse(value);return Array.isArray(x)?x.map(String):[]}catch{return[]}}
function clean(value:string|null,max:number){const x=value?.trim().slice(0,max);return x||null}function allowed<T extends string>(value:string|null,values:readonly T[]):T|null{return value&&values.includes(value as T)?value as T:null}function message(error:unknown){return error instanceof Error?error.message.slice(0,500):String(error).slice(0,500)}
