"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import styles from "../documentation.module.css";

type NodeType="paper"|"researcher"|"topic"|"institution"|"opportunity";
type GraphNode={id:string;type:NodeType;label:string;labelEn?:string;subtitle?:string;url?:string};
type GraphEdge={source:string;target:string;relation:string};
type Point=GraphNode&{x:number;y:number};
const COLORS:Record<NodeType,string>={paper:"#62e7d4",researcher:"#c9ff6b",topic:"#ffd76b",institution:"#a9b7ff",opportunity:"#ff9f80"};
const LABELS:Record<NodeType,string>={paper:"论文",researcher:"导师",topic:"研究方向",institution:"机构/实验室",opportunity:"机会"};

export default function KnowledgeGraphExplorer(){
  const canvasRef=useRef<HTMLCanvasElement>(null);const wrapRef=useRef<HTMLDivElement>(null);const[items,setItems]=useState<GraphNode[]>([]);const[edges,setEdges]=useState<GraphEdge[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selected,setSelected]=useState<GraphNode|null>(null);const[enabled,setEnabled]=useState<Set<NodeType>>(new Set(Object.keys(LABELS) as NodeType[]));
  const visibleNodes=useMemo(()=>items.filter((node)=>enabled.has(node.type)),[items,enabled]);const visibleIds=useMemo(()=>new Set(visibleNodes.map((node)=>node.id)),[visibleNodes]);const visibleEdges=useMemo(()=>edges.filter((edge)=>visibleIds.has(edge.source)&&visibleIds.has(edge.target)),[edges,visibleIds]);
  useEffect(()=>{fetch("/api/knowledge-graph").then(async(response)=>{if(!response.ok)throw new Error("知识图谱暂不可用");return response.json() as Promise<{nodes?:GraphNode[];edges?:GraphEdge[]}>}).then((data)=>{setItems(data.nodes??[]);setEdges(data.edges??[])}).catch((reason:Error)=>setError(reason.message)).finally(()=>setLoading(false))},[]);
  useEffect(()=>{const canvas=canvasRef.current;const wrap=wrapRef.current;if(!canvas||!wrap||visibleNodes.length===0)return;const render=()=>{const rect=wrap.getBoundingClientRect();const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;const context=canvas.getContext("2d");if(!context)return;context.scale(ratio,ratio);context.clearRect(0,0,rect.width,rect.height);drawGraph(context,layout(visibleNodes,rect.width,rect.height),visibleEdges,selected?.id)};render();const observer=new ResizeObserver(render);observer.observe(wrap);return()=>observer.disconnect()},[visibleNodes,visibleEdges,selected]);
  function selectAt(event:React.PointerEvent<HTMLCanvasElement>){const rect=event.currentTarget.getBoundingClientRect();const points=layout(visibleNodes,rect.width,rect.height);const x=event.clientX-rect.left,y=event.clientY-rect.top;const hit=points.reduce<{node:Point|null;distance:number}>((best,node)=>{const distance=Math.hypot(node.x-x,node.y-y);return distance<best.distance?{node,distance}:best},{node:null,distance:30});setSelected(hit.node)}
  function toggle(type:NodeType){setEnabled((current)=>{const next=new Set(current);if(next.has(type)){if(next.size>1)next.delete(type)}else next.add(type);return next})}
  return <section className={styles.section}><div className={styles.sectionHead}><h2>关系网络</h2><p>点击节点查看详情。连线来自论文作者、导师研究方向、机构归属和机会发布关系；候选论文仍保留核验边界。</p></div><div className={styles.graphFilters}>{(Object.keys(LABELS) as NodeType[]).map((type)=><button key={type} className={enabled.has(type)?styles.graphFilterActive:""} onClick={()=>toggle(type)}><i style={{background:COLORS[type]}}/>{LABELS[type]}</button>)}</div>{loading&&<p className={styles.loading}>正在构建知识图谱…</p>}{error&&<p className={`${styles.state} ${styles.stateError}`}>{error}</p>}{!loading&&!error&&<div className={styles.graphLayout}><div ref={wrapRef} className={styles.graphCanvasWrap}><canvas ref={canvasRef} onPointerUp={selectAt} aria-label="论文、导师、研究方向、机构与机会知识图谱" role="img"/><span className={styles.graphHint}>点击节点 · 颜色区分实体类型</span></div><aside className={styles.graphInspector}>{selected?<><span style={{color:COLORS[selected.type]}}>{LABELS[selected.type]}</span><h3>{selected.label}</h3>{selected.labelEn&&<p lang="en">{selected.labelEn}</p>}{selected.subtitle&&<p>{selected.subtitle}</p>}<dl><div><dt>连接数</dt><dd>{edges.filter((edge)=>edge.source===selected.id||edge.target===selected.id).length}</dd></div></dl>{selected.url&&<a href={selected.url} target="_blank" rel="noreferrer">查看官方来源 ↗</a>}</>:<><span>KNOWLEDGE GRAPH</span><h3>选择一个节点</h3><p>桌面端点击画布；手机端也可使用下方可访问列表。</p></>}</aside></div>}<div className={styles.graphAccessibleList}>{visibleNodes.slice(0,80).map((node)=><button key={node.id} onClick={()=>setSelected(node)}><i style={{background:COLORS[node.type]}}/><span><b>{node.label}</b><small>{LABELS[node.type]}{node.subtitle?` · ${node.subtitle}`:""}</small></span></button>)}</div></section>
}

function layout(nodes:GraphNode[],width:number,height:number):Point[]{const groups=new Map<NodeType,GraphNode[]>();for(const node of nodes){const group=groups.get(node.type)??[];group.push(node);groups.set(node.type,group)}const centers:Record<NodeType,[number,number]>={institution:[.18,.25],researcher:[.43,.28],topic:[.53,.65],paper:[.78,.35],opportunity:[.24,.73]};const points:Point[]=[];for(const[type,group]of groups){const[cx,cy]=centers[type];const radius=Math.min(width,height)*(group.length>20?.25:.15);group.forEach((node,index)=>{const angle=(index/group.length)*Math.PI*2+(type.charCodeAt(0)%7);const ring=1+(index%3)*.32;points.push({...node,x:width*cx+Math.cos(angle)*radius*ring,y:height*cy+Math.sin(angle)*radius*ring})})}return points}
function drawGraph(context:CanvasRenderingContext2D,nodes:Point[],edges:GraphEdge[],selected?:string){const map=new Map(nodes.map((node)=>[node.id,node]));context.lineWidth=.7;for(const edge of edges){const source=map.get(edge.source),target=map.get(edge.target);if(!source||!target)continue;context.strokeStyle=selected&&(edge.source===selected||edge.target===selected)?"rgba(201,255,107,.75)":"rgba(161,190,181,.12)";context.beginPath();context.moveTo(source.x,source.y);context.lineTo(target.x,target.y);context.stroke()}for(const node of nodes){const active=node.id===selected;context.fillStyle=COLORS[node.type];context.globalAlpha=active?1:.78;context.beginPath();context.arc(node.x,node.y,active?7:node.type==="topic"?3.5:5,0,Math.PI*2);context.fill();if(active){context.strokeStyle="#fff";context.lineWidth=2;context.stroke()}context.globalAlpha=1}context.font="11px ui-monospace, SFMono-Regular, Menlo, monospace";context.fillStyle="rgba(220,236,230,.86)";for(const node of nodes.filter((item)=>item.id===selected||item.type==="researcher"||item.type==="institution").slice(0,34)){context.fillText(short(node.label,18),node.x+9,node.y+4)}}
function short(value:string,length:number){return value.length>length?`${value.slice(0,length)}…`:value}
